server:
  port: 8080
  
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hrm?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    enabled: false
  mvc:
    static-path-pattern: /static/**
    view:
      #配置视图解析器前缀
      prefix: /WEB-INF/jsp/
      #配置视图解析器后缀缀
      suffix: .jsp
  #资源路径
  resources:
    static-locations:
    - classpath:/static/
  jackson:
    time-zone:
      GMT+8
  ##网易163邮箱配置
  mail:
    host: smtp.163.com #发送邮件服务器
    username: luckylas@163.com #发送邮件的邮箱地址
    password: USKRHBHTVTFPZQOV #客户端授权码
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          ssl:
            enable: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
    port: 465
    from: luckylas@163.com #配置发送邮件的邮箱地址，用于代码读取此值
      
       
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.lqs.entity

#pagehelper分页插件
#pagehelper:
 #   helperDialect: mysql
  #  reasonable: true
  #  supportMethodsArguments: true
  #  params: count=countSql





