server:
  port: 8080
  
spring:
  datasource:
    name: test
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&amp;characterEncoding=utf-8&amp;useSSL=false&amp;serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    enabled: false
  mvc:
    view:
      #配置视图解析器前缀
      prefix: /WEB-INF/jsp/
      #配置视图解析器后缀缀
      suffix: .jsp
       
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.lqs.entity

#pagehelper分页插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
