server:
  port: 8080
  
spring:
  datasource:
    name: test
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&amp;characterEncoding=utf-8&amp;useSSL=false&amp;serverTimezone=UTC
    
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
       
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.lqs.entity

#pagehelper分页插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
