package com.lqs.hrm.mapper;

import com.lqs.hrm.entity.CountAttendanceDepartmant;
import com.lqs.hrm.entity.CountAttendanceDepartmantExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CountAttendanceDepartmantMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table count_attendance_departmant
     *
     * @mbg.generated Tue May 26 23:34:06 CST 2020
     */
    long countByExample(CountAttendanceDepartmantExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table count_attendance_departmant
     *
     * @mbg.generated Tue May 26 23:34:06 CST 2020
     */
    int deleteByExample(CountAttendanceDepartmantExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table count_attendance_departmant
     *
     * @mbg.generated Tue May 26 23:34:06 CST 2020
     */
    int deleteByPrimaryKey(Integer cadId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table count_attendance_departmant
     *
     * @mbg.generated Tue May 26 23:34:06 CST 2020
     */
    int insert(CountAttendanceDepartmant record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table count_attendance_departmant
     *
     * @mbg.generated Tue May 26 23:34:06 CST 2020
     */
    int insertSelective(CountAttendanceDepartmant record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table count_attendance_departmant
     *
     * @mbg.generated Tue May 26 23:34:06 CST 2020
     */
    List<CountAttendanceDepartmant> selectByExample(CountAttendanceDepartmantExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table count_attendance_departmant
     *
     * @mbg.generated Tue May 26 23:34:06 CST 2020
     */
    CountAttendanceDepartmant selectByPrimaryKey(Integer cadId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table count_attendance_departmant
     *
     * @mbg.generated Tue May 26 23:34:06 CST 2020
     */
    int updateByExampleSelective(@Param("record") CountAttendanceDepartmant record, @Param("example") CountAttendanceDepartmantExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table count_attendance_departmant
     *
     * @mbg.generated Tue May 26 23:34:06 CST 2020
     */
    int updateByExample(@Param("record") CountAttendanceDepartmant record, @Param("example") CountAttendanceDepartmantExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table count_attendance_departmant
     *
     * @mbg.generated Tue May 26 23:34:06 CST 2020
     */
    int updateByPrimaryKeySelective(CountAttendanceDepartmant record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table count_attendance_departmant
     *
     * @mbg.generated Tue May 26 23:34:06 CST 2020
     */
    int updateByPrimaryKey(CountAttendanceDepartmant record);
}