package com.lqs.hrm.mapper;

import com.lqs.hrm.entity.EmployeeContract;
import com.lqs.hrm.entity.EmployeeContractExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EmployeeContractMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_contract
     *
     * @mbg.generated Tue May 19 13:47:12 CST 2020
     */
    long countByExample(EmployeeContractExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_contract
     *
     * @mbg.generated Tue May 19 13:47:12 CST 2020
     */
    int deleteByExample(EmployeeContractExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_contract
     *
     * @mbg.generated Tue May 19 13:47:12 CST 2020
     */
    int deleteByPrimaryKey(Integer ecId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_contract
     *
     * @mbg.generated Tue May 19 13:47:12 CST 2020
     */
    int insert(EmployeeContract record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_contract
     *
     * @mbg.generated Tue May 19 13:47:12 CST 2020
     */
    int insertSelective(EmployeeContract record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_contract
     *
     * @mbg.generated Tue May 19 13:47:12 CST 2020
     */
    List<EmployeeContract> selectByExample(EmployeeContractExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_contract
     *
     * @mbg.generated Tue May 19 13:47:12 CST 2020
     */
    EmployeeContract selectByPrimaryKey(Integer ecId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_contract
     *
     * @mbg.generated Tue May 19 13:47:12 CST 2020
     */
    int updateByExampleSelective(@Param("record") EmployeeContract record, @Param("example") EmployeeContractExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_contract
     *
     * @mbg.generated Tue May 19 13:47:12 CST 2020
     */
    int updateByExample(@Param("record") EmployeeContract record, @Param("example") EmployeeContractExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_contract
     *
     * @mbg.generated Tue May 19 13:47:12 CST 2020
     */
    int updateByPrimaryKeySelective(EmployeeContract record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_contract
     *
     * @mbg.generated Tue May 19 13:47:12 CST 2020
     */
    int updateByPrimaryKey(EmployeeContract record);
}