package com.lqs.hrm.mapper;

import com.lqs.hrm.entity.EmployeeEntry;
import com.lqs.hrm.entity.EmployeeEntryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EmployeeEntryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_entry
     *
     * @mbg.generated Wed May 20 00:13:03 CST 2020
     */
    long countByExample(EmployeeEntryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_entry
     *
     * @mbg.generated Wed May 20 00:13:03 CST 2020
     */
    int deleteByExample(EmployeeEntryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_entry
     *
     * @mbg.generated Wed May 20 00:13:03 CST 2020
     */
    int deleteByPrimaryKey(Integer eeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_entry
     *
     * @mbg.generated Wed May 20 00:13:03 CST 2020
     */
    int insert(EmployeeEntry record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_entry
     *
     * @mbg.generated Wed May 20 00:13:03 CST 2020
     */
    int insertSelective(EmployeeEntry record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_entry
     *
     * @mbg.generated Wed May 20 00:13:03 CST 2020
     */
    List<EmployeeEntry> selectByExample(EmployeeEntryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_entry
     *
     * @mbg.generated Wed May 20 00:13:03 CST 2020
     */
    EmployeeEntry selectByPrimaryKey(Integer eeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_entry
     *
     * @mbg.generated Wed May 20 00:13:03 CST 2020
     */
    int updateByExampleSelective(@Param("record") EmployeeEntry record, @Param("example") EmployeeEntryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_entry
     *
     * @mbg.generated Wed May 20 00:13:03 CST 2020
     */
    int updateByExample(@Param("record") EmployeeEntry record, @Param("example") EmployeeEntryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_entry
     *
     * @mbg.generated Wed May 20 00:13:03 CST 2020
     */
    int updateByPrimaryKeySelective(EmployeeEntry record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_entry
     *
     * @mbg.generated Wed May 20 00:13:03 CST 2020
     */
    int updateByPrimaryKey(EmployeeEntry record);
}