package com.lqs.hrm.entity;

import java.util.Date;

/**
 * 考勤时间设置信息实体类
 * @author luckyliuqs
 *
 */
public class AttendanceTime {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attendance_time.at_id
     *
     * @mbg.generated Mon May 25 19:32:58 CST 2020
     */
    private Integer atId;

    /**
     * 早上最早开始时间
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attendance_time.morning_early
     *
     * @mbg.generated Mon May 25 19:32:58 CST 2020
     */
    private String morningEarly;

    /**
     * 早上最晚开始时间
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attendance_time.morning_last
     *
     * @mbg.generated Mon May 25 19:32:58 CST 2020
     */
    private String morningLast;

    /**
     * 下午最早开始时间
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attendance_time.afternoon_early
     *
     * @mbg.generated Mon May 25 19:32:58 CST 2020
     */
    private String afternoonEarly;

    /**
     * 下午最晚开始时间
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attendance_time.afternoon_last
     *
     * @mbg.generated Mon May 25 19:32:58 CST 2020
     */
    private String afternoonLast;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attendance_time.last_operator_date
     *
     * @mbg.generated Mon May 25 19:32:58 CST 2020
     */
    private Date lastOperatorDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attendance_time.operator_empJobId
     *
     * @mbg.generated Mon May 25 19:32:58 CST 2020
     */
    private String operatorEmpjobid;
    
    /**
     * 操作人名称
     */
    private String operatorEmpName = "";

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attendance_time.at_id
     *
     * @return the value of attendance_time.at_id
     *
     * @mbg.generated Mon May 25 19:32:58 CST 2020
     */
    public Integer getAtId() {
        return atId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attendance_time.at_id
     *
     * @param atId the value for attendance_time.at_id
     *
     * @mbg.generated Mon May 25 19:32:58 CST 2020
     */
    public void setAtId(Integer atId) {
        this.atId = atId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attendance_time.morning_early
     *
     * @return the value of attendance_time.morning_early
     *
     * @mbg.generated Mon May 25 19:32:58 CST 2020
     */
    public String getMorningEarly() {
        return morningEarly;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attendance_time.morning_early
     *
     * @param morningEarly the value for attendance_time.morning_early
     *
     * @mbg.generated Mon May 25 19:32:58 CST 2020
     */
    public void setMorningEarly(String morningEarly) {
        this.morningEarly = morningEarly;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attendance_time.morning_last
     *
     * @return the value of attendance_time.morning_last
     *
     * @mbg.generated Mon May 25 19:32:58 CST 2020
     */
    public String getMorningLast() {
        return morningLast;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attendance_time.morning_last
     *
     * @param morningLast the value for attendance_time.morning_last
     *
     * @mbg.generated Mon May 25 19:32:58 CST 2020
     */
    public void setMorningLast(String morningLast) {
        this.morningLast = morningLast;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attendance_time.afternoon_early
     *
     * @return the value of attendance_time.afternoon_early
     *
     * @mbg.generated Mon May 25 19:32:58 CST 2020
     */
    public String getAfternoonEarly() {
        return afternoonEarly;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attendance_time.afternoon_early
     *
     * @param afternoonEarly the value for attendance_time.afternoon_early
     *
     * @mbg.generated Mon May 25 19:32:58 CST 2020
     */
    public void setAfternoonEarly(String afternoonEarly) {
        this.afternoonEarly = afternoonEarly;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attendance_time.afternoon_last
     *
     * @return the value of attendance_time.afternoon_last
     *
     * @mbg.generated Mon May 25 19:32:58 CST 2020
     */
    public String getAfternoonLast() {
        return afternoonLast;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attendance_time.afternoon_last
     *
     * @param afternoonLast the value for attendance_time.afternoon_last
     *
     * @mbg.generated Mon May 25 19:32:58 CST 2020
     */
    public void setAfternoonLast(String afternoonLast) {
        this.afternoonLast = afternoonLast;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attendance_time.last_operator_date
     *
     * @return the value of attendance_time.last_operator_date
     *
     * @mbg.generated Mon May 25 19:32:58 CST 2020
     */
    public Date getLastOperatorDate() {
        return lastOperatorDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attendance_time.last_operator_date
     *
     * @param lastOperatorDate the value for attendance_time.last_operator_date
     *
     * @mbg.generated Mon May 25 19:32:58 CST 2020
     */
    public void setLastOperatorDate(Date lastOperatorDate) {
        this.lastOperatorDate = lastOperatorDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attendance_time.operator_empJobId
     *
     * @return the value of attendance_time.operator_empJobId
     *
     * @mbg.generated Mon May 25 19:32:58 CST 2020
     */
    public String getOperatorEmpjobid() {
        return operatorEmpjobid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attendance_time.operator_empJobId
     *
     * @param operatorEmpjobid the value for attendance_time.operator_empJobId
     *
     * @mbg.generated Mon May 25 19:32:58 CST 2020
     */
    public void setOperatorEmpjobid(String operatorEmpjobid) {
        this.operatorEmpjobid = operatorEmpjobid;
    }

	public String getOperatorEmpName() {
		return operatorEmpName;
	}

	public void setOperatorEmpName(String operatorEmpName) {
		this.operatorEmpName = operatorEmpName;
	}
    
}