package com.lqs.hrm.entity;

import java.util.Date;
import java.util.List;

/**
 * 职工考勤信息实体类
 * @author luckyliuqs
 *
 */
public class AttendanceEmployee {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column attendance_employee.ae_id
	 * @mbg.generated  Mon May 25 19:54:19 CST 2020
	 */
	private Integer aeId;

	/**
	 * 签到日期
	 * This field was generated by MyBatis Generator. This field corresponds to the database column attendance_employee.date
	 * @mbg.generated  Mon May 25 19:54:19 CST 2020
	 */
	private Date date;

	/** 
	 * 签到时间
	 * This field was generated by MyBatis Generator. This field corresponds to the database column attendance_employee.sign_time
	 * @mbg.generated  Mon May 25 19:54:19 CST 2020
	 */
	private Date signTime;

	/**
	 * 签退时间
	 * This field was generated by MyBatis Generator. This field corresponds to the database column attendance_employee.logout_time
	 * @mbg.generated  Mon May 25 19:54:19 CST 2020
	 */
	private Date logoutTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column attendance_employee.emp_jobId
	 * @mbg.generated  Mon May 25 19:54:19 CST 2020
	 */
	private String empJobid;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column attendance_employee.status_id
	 * @mbg.generated  Mon May 25 19:54:19 CST 2020
	 */
	private Integer statusId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column attendance_employee.ae_id
	 * @return  the value of attendance_employee.ae_id
	 * @mbg.generated  Mon May 25 19:54:19 CST 2020
	 */
	public Integer getAeId() {
		return aeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column attendance_employee.ae_id
	 * @param aeId  the value for attendance_employee.ae_id
	 * @mbg.generated  Mon May 25 19:54:19 CST 2020
	 */
	public void setAeId(Integer aeId) {
		this.aeId = aeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column attendance_employee.date
	 * @return  the value of attendance_employee.date
	 * @mbg.generated  Mon May 25 19:54:19 CST 2020
	 */
	public Date getDate() {
		return date;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column attendance_employee.date
	 * @param date  the value for attendance_employee.date
	 * @mbg.generated  Mon May 25 19:54:19 CST 2020
	 */
	public void setDate(Date date) {
		this.date = date;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column attendance_employee.sign_time
	 * @return  the value of attendance_employee.sign_time
	 * @mbg.generated  Mon May 25 19:54:19 CST 2020
	 */
	public Date getSignTime() {
		return signTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column attendance_employee.sign_time
	 * @param signTime  the value for attendance_employee.sign_time
	 * @mbg.generated  Mon May 25 19:54:19 CST 2020
	 */
	public void setSignTime(Date signTime) {
		this.signTime = signTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column attendance_employee.logout_time
	 * @return  the value of attendance_employee.logout_time
	 * @mbg.generated  Mon May 25 19:54:19 CST 2020
	 */
	public Date getLogoutTime() {
		return logoutTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column attendance_employee.logout_time
	 * @param logoutTime  the value for attendance_employee.logout_time
	 * @mbg.generated  Mon May 25 19:54:19 CST 2020
	 */
	public void setLogoutTime(Date logoutTime) {
		this.logoutTime = logoutTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column attendance_employee.emp_jobId
	 * @return  the value of attendance_employee.emp_jobId
	 * @mbg.generated  Mon May 25 19:54:19 CST 2020
	 */
	public String getEmpJobid() {
		return empJobid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column attendance_employee.emp_jobId
	 * @param empJobid  the value for attendance_employee.emp_jobId
	 * @mbg.generated  Mon May 25 19:54:19 CST 2020
	 */
	public void setEmpJobid(String empJobid) {
		this.empJobid = empJobid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column attendance_employee.status_id
	 * @return  the value of attendance_employee.status_id
	 * @mbg.generated  Mon May 25 19:54:19 CST 2020
	 */
	public Integer getStatusId() {
		return statusId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column attendance_employee.status_id
	 * @param statusId  the value for attendance_employee.status_id
	 * @mbg.generated  Mon May 25 19:54:19 CST 2020
	 */
	public void setStatusId(Integer statusId) {
		this.statusId = statusId;
	}

	/**
     * 职工人姓名
     */
    private String empName = "";

    /**
     * 状态名称
     */
    private String statusName = "";
    
    /**
     * 职工所属部门List集合
     */
    private List<Department> departmentList;
    
    /**
     * 职工所属部门名称List集合的Str形式
     */
    private String deptNameListStr;
    
    /**
     * 职工所属职位id
     */
    private List<Position> positionList;
    
    /**
     * 职工所属部职位名称List集合的Str形式
     */
    private String positionNameListStr;
    

    public String getEmpName() {
		return empName;
	}

	public void setEmpName(String empName) {
		this.empName = empName;
	}

	public String getStatusName() {
		return statusName;
	}

	public void setStatusName(String statusName) {
		this.statusName = statusName;
	}

	public List<Department> getDepartmentList() {
		return departmentList;
	}

	public void setDepartmentList(List<Department> departmentList) {
		this.departmentList = departmentList;
	}

	public String getDeptNameListStr() {
		return deptNameListStr;
	}

	public void setDeptNameListStr(String deptNameListStr) {
		this.deptNameListStr = deptNameListStr;
	}

	public List<Position> getPositionList() {
		return positionList;
	}

	public void setPositionList(List<Position> positionList) {
		this.positionList = positionList;
	}

	public String getPositionNameListStr() {
		return positionNameListStr;
	}

	public void setPositionNameListStr(String positionNameListStr) {
		this.positionNameListStr = positionNameListStr;
	}
	
}