package com.lqs.hrm.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class AttendanceTimeExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table attendance_time
     *
     * @mbg.generated Mon May 25 19:32:58 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table attendance_time
     *
     * @mbg.generated Mon May 25 19:32:58 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table attendance_time
     *
     * @mbg.generated Mon May 25 19:32:58 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attendance_time
     *
     * @mbg.generated Mon May 25 19:32:58 CST 2020
     */
    public AttendanceTimeExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attendance_time
     *
     * @mbg.generated Mon May 25 19:32:58 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attendance_time
     *
     * @mbg.generated Mon May 25 19:32:58 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attendance_time
     *
     * @mbg.generated Mon May 25 19:32:58 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attendance_time
     *
     * @mbg.generated Mon May 25 19:32:58 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attendance_time
     *
     * @mbg.generated Mon May 25 19:32:58 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attendance_time
     *
     * @mbg.generated Mon May 25 19:32:58 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attendance_time
     *
     * @mbg.generated Mon May 25 19:32:58 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attendance_time
     *
     * @mbg.generated Mon May 25 19:32:58 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attendance_time
     *
     * @mbg.generated Mon May 25 19:32:58 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attendance_time
     *
     * @mbg.generated Mon May 25 19:32:58 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table attendance_time
     *
     * @mbg.generated Mon May 25 19:32:58 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andAtIdIsNull() {
            addCriterion("at_id is null");
            return (Criteria) this;
        }

        public Criteria andAtIdIsNotNull() {
            addCriterion("at_id is not null");
            return (Criteria) this;
        }

        public Criteria andAtIdEqualTo(Integer value) {
            addCriterion("at_id =", value, "atId");
            return (Criteria) this;
        }

        public Criteria andAtIdNotEqualTo(Integer value) {
            addCriterion("at_id <>", value, "atId");
            return (Criteria) this;
        }

        public Criteria andAtIdGreaterThan(Integer value) {
            addCriterion("at_id >", value, "atId");
            return (Criteria) this;
        }

        public Criteria andAtIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("at_id >=", value, "atId");
            return (Criteria) this;
        }

        public Criteria andAtIdLessThan(Integer value) {
            addCriterion("at_id <", value, "atId");
            return (Criteria) this;
        }

        public Criteria andAtIdLessThanOrEqualTo(Integer value) {
            addCriterion("at_id <=", value, "atId");
            return (Criteria) this;
        }

        public Criteria andAtIdIn(List<Integer> values) {
            addCriterion("at_id in", values, "atId");
            return (Criteria) this;
        }

        public Criteria andAtIdNotIn(List<Integer> values) {
            addCriterion("at_id not in", values, "atId");
            return (Criteria) this;
        }

        public Criteria andAtIdBetween(Integer value1, Integer value2) {
            addCriterion("at_id between", value1, value2, "atId");
            return (Criteria) this;
        }

        public Criteria andAtIdNotBetween(Integer value1, Integer value2) {
            addCriterion("at_id not between", value1, value2, "atId");
            return (Criteria) this;
        }

        public Criteria andMorningEarlyIsNull() {
            addCriterion("morning_early is null");
            return (Criteria) this;
        }

        public Criteria andMorningEarlyIsNotNull() {
            addCriterion("morning_early is not null");
            return (Criteria) this;
        }

        public Criteria andMorningEarlyEqualTo(String value) {
            addCriterion("morning_early =", value, "morningEarly");
            return (Criteria) this;
        }

        public Criteria andMorningEarlyNotEqualTo(String value) {
            addCriterion("morning_early <>", value, "morningEarly");
            return (Criteria) this;
        }

        public Criteria andMorningEarlyGreaterThan(String value) {
            addCriterion("morning_early >", value, "morningEarly");
            return (Criteria) this;
        }

        public Criteria andMorningEarlyGreaterThanOrEqualTo(String value) {
            addCriterion("morning_early >=", value, "morningEarly");
            return (Criteria) this;
        }

        public Criteria andMorningEarlyLessThan(String value) {
            addCriterion("morning_early <", value, "morningEarly");
            return (Criteria) this;
        }

        public Criteria andMorningEarlyLessThanOrEqualTo(String value) {
            addCriterion("morning_early <=", value, "morningEarly");
            return (Criteria) this;
        }

        public Criteria andMorningEarlyLike(String value) {
            addCriterion("morning_early like", value, "morningEarly");
            return (Criteria) this;
        }

        public Criteria andMorningEarlyNotLike(String value) {
            addCriterion("morning_early not like", value, "morningEarly");
            return (Criteria) this;
        }

        public Criteria andMorningEarlyIn(List<String> values) {
            addCriterion("morning_early in", values, "morningEarly");
            return (Criteria) this;
        }

        public Criteria andMorningEarlyNotIn(List<String> values) {
            addCriterion("morning_early not in", values, "morningEarly");
            return (Criteria) this;
        }

        public Criteria andMorningEarlyBetween(String value1, String value2) {
            addCriterion("morning_early between", value1, value2, "morningEarly");
            return (Criteria) this;
        }

        public Criteria andMorningEarlyNotBetween(String value1, String value2) {
            addCriterion("morning_early not between", value1, value2, "morningEarly");
            return (Criteria) this;
        }

        public Criteria andMorningLastIsNull() {
            addCriterion("morning_last is null");
            return (Criteria) this;
        }

        public Criteria andMorningLastIsNotNull() {
            addCriterion("morning_last is not null");
            return (Criteria) this;
        }

        public Criteria andMorningLastEqualTo(String value) {
            addCriterion("morning_last =", value, "morningLast");
            return (Criteria) this;
        }

        public Criteria andMorningLastNotEqualTo(String value) {
            addCriterion("morning_last <>", value, "morningLast");
            return (Criteria) this;
        }

        public Criteria andMorningLastGreaterThan(String value) {
            addCriterion("morning_last >", value, "morningLast");
            return (Criteria) this;
        }

        public Criteria andMorningLastGreaterThanOrEqualTo(String value) {
            addCriterion("morning_last >=", value, "morningLast");
            return (Criteria) this;
        }

        public Criteria andMorningLastLessThan(String value) {
            addCriterion("morning_last <", value, "morningLast");
            return (Criteria) this;
        }

        public Criteria andMorningLastLessThanOrEqualTo(String value) {
            addCriterion("morning_last <=", value, "morningLast");
            return (Criteria) this;
        }

        public Criteria andMorningLastLike(String value) {
            addCriterion("morning_last like", value, "morningLast");
            return (Criteria) this;
        }

        public Criteria andMorningLastNotLike(String value) {
            addCriterion("morning_last not like", value, "morningLast");
            return (Criteria) this;
        }

        public Criteria andMorningLastIn(List<String> values) {
            addCriterion("morning_last in", values, "morningLast");
            return (Criteria) this;
        }

        public Criteria andMorningLastNotIn(List<String> values) {
            addCriterion("morning_last not in", values, "morningLast");
            return (Criteria) this;
        }

        public Criteria andMorningLastBetween(String value1, String value2) {
            addCriterion("morning_last between", value1, value2, "morningLast");
            return (Criteria) this;
        }

        public Criteria andMorningLastNotBetween(String value1, String value2) {
            addCriterion("morning_last not between", value1, value2, "morningLast");
            return (Criteria) this;
        }

        public Criteria andAfternoonEarlyIsNull() {
            addCriterion("afternoon_early is null");
            return (Criteria) this;
        }

        public Criteria andAfternoonEarlyIsNotNull() {
            addCriterion("afternoon_early is not null");
            return (Criteria) this;
        }

        public Criteria andAfternoonEarlyEqualTo(String value) {
            addCriterion("afternoon_early =", value, "afternoonEarly");
            return (Criteria) this;
        }

        public Criteria andAfternoonEarlyNotEqualTo(String value) {
            addCriterion("afternoon_early <>", value, "afternoonEarly");
            return (Criteria) this;
        }

        public Criteria andAfternoonEarlyGreaterThan(String value) {
            addCriterion("afternoon_early >", value, "afternoonEarly");
            return (Criteria) this;
        }

        public Criteria andAfternoonEarlyGreaterThanOrEqualTo(String value) {
            addCriterion("afternoon_early >=", value, "afternoonEarly");
            return (Criteria) this;
        }

        public Criteria andAfternoonEarlyLessThan(String value) {
            addCriterion("afternoon_early <", value, "afternoonEarly");
            return (Criteria) this;
        }

        public Criteria andAfternoonEarlyLessThanOrEqualTo(String value) {
            addCriterion("afternoon_early <=", value, "afternoonEarly");
            return (Criteria) this;
        }

        public Criteria andAfternoonEarlyLike(String value) {
            addCriterion("afternoon_early like", value, "afternoonEarly");
            return (Criteria) this;
        }

        public Criteria andAfternoonEarlyNotLike(String value) {
            addCriterion("afternoon_early not like", value, "afternoonEarly");
            return (Criteria) this;
        }

        public Criteria andAfternoonEarlyIn(List<String> values) {
            addCriterion("afternoon_early in", values, "afternoonEarly");
            return (Criteria) this;
        }

        public Criteria andAfternoonEarlyNotIn(List<String> values) {
            addCriterion("afternoon_early not in", values, "afternoonEarly");
            return (Criteria) this;
        }

        public Criteria andAfternoonEarlyBetween(String value1, String value2) {
            addCriterion("afternoon_early between", value1, value2, "afternoonEarly");
            return (Criteria) this;
        }

        public Criteria andAfternoonEarlyNotBetween(String value1, String value2) {
            addCriterion("afternoon_early not between", value1, value2, "afternoonEarly");
            return (Criteria) this;
        }

        public Criteria andAfternoonLastIsNull() {
            addCriterion("afternoon_last is null");
            return (Criteria) this;
        }

        public Criteria andAfternoonLastIsNotNull() {
            addCriterion("afternoon_last is not null");
            return (Criteria) this;
        }

        public Criteria andAfternoonLastEqualTo(String value) {
            addCriterion("afternoon_last =", value, "afternoonLast");
            return (Criteria) this;
        }

        public Criteria andAfternoonLastNotEqualTo(String value) {
            addCriterion("afternoon_last <>", value, "afternoonLast");
            return (Criteria) this;
        }

        public Criteria andAfternoonLastGreaterThan(String value) {
            addCriterion("afternoon_last >", value, "afternoonLast");
            return (Criteria) this;
        }

        public Criteria andAfternoonLastGreaterThanOrEqualTo(String value) {
            addCriterion("afternoon_last >=", value, "afternoonLast");
            return (Criteria) this;
        }

        public Criteria andAfternoonLastLessThan(String value) {
            addCriterion("afternoon_last <", value, "afternoonLast");
            return (Criteria) this;
        }

        public Criteria andAfternoonLastLessThanOrEqualTo(String value) {
            addCriterion("afternoon_last <=", value, "afternoonLast");
            return (Criteria) this;
        }

        public Criteria andAfternoonLastLike(String value) {
            addCriterion("afternoon_last like", value, "afternoonLast");
            return (Criteria) this;
        }

        public Criteria andAfternoonLastNotLike(String value) {
            addCriterion("afternoon_last not like", value, "afternoonLast");
            return (Criteria) this;
        }

        public Criteria andAfternoonLastIn(List<String> values) {
            addCriterion("afternoon_last in", values, "afternoonLast");
            return (Criteria) this;
        }

        public Criteria andAfternoonLastNotIn(List<String> values) {
            addCriterion("afternoon_last not in", values, "afternoonLast");
            return (Criteria) this;
        }

        public Criteria andAfternoonLastBetween(String value1, String value2) {
            addCriterion("afternoon_last between", value1, value2, "afternoonLast");
            return (Criteria) this;
        }

        public Criteria andAfternoonLastNotBetween(String value1, String value2) {
            addCriterion("afternoon_last not between", value1, value2, "afternoonLast");
            return (Criteria) this;
        }

        public Criteria andLastOperatorDateIsNull() {
            addCriterion("last_operator_date is null");
            return (Criteria) this;
        }

        public Criteria andLastOperatorDateIsNotNull() {
            addCriterion("last_operator_date is not null");
            return (Criteria) this;
        }

        public Criteria andLastOperatorDateEqualTo(Date value) {
            addCriterion("last_operator_date =", value, "lastOperatorDate");
            return (Criteria) this;
        }

        public Criteria andLastOperatorDateNotEqualTo(Date value) {
            addCriterion("last_operator_date <>", value, "lastOperatorDate");
            return (Criteria) this;
        }

        public Criteria andLastOperatorDateGreaterThan(Date value) {
            addCriterion("last_operator_date >", value, "lastOperatorDate");
            return (Criteria) this;
        }

        public Criteria andLastOperatorDateGreaterThanOrEqualTo(Date value) {
            addCriterion("last_operator_date >=", value, "lastOperatorDate");
            return (Criteria) this;
        }

        public Criteria andLastOperatorDateLessThan(Date value) {
            addCriterion("last_operator_date <", value, "lastOperatorDate");
            return (Criteria) this;
        }

        public Criteria andLastOperatorDateLessThanOrEqualTo(Date value) {
            addCriterion("last_operator_date <=", value, "lastOperatorDate");
            return (Criteria) this;
        }

        public Criteria andLastOperatorDateIn(List<Date> values) {
            addCriterion("last_operator_date in", values, "lastOperatorDate");
            return (Criteria) this;
        }

        public Criteria andLastOperatorDateNotIn(List<Date> values) {
            addCriterion("last_operator_date not in", values, "lastOperatorDate");
            return (Criteria) this;
        }

        public Criteria andLastOperatorDateBetween(Date value1, Date value2) {
            addCriterion("last_operator_date between", value1, value2, "lastOperatorDate");
            return (Criteria) this;
        }

        public Criteria andLastOperatorDateNotBetween(Date value1, Date value2) {
            addCriterion("last_operator_date not between", value1, value2, "lastOperatorDate");
            return (Criteria) this;
        }

        public Criteria andOperatorEmpjobidIsNull() {
            addCriterion("operator_empJobId is null");
            return (Criteria) this;
        }

        public Criteria andOperatorEmpjobidIsNotNull() {
            addCriterion("operator_empJobId is not null");
            return (Criteria) this;
        }

        public Criteria andOperatorEmpjobidEqualTo(String value) {
            addCriterion("operator_empJobId =", value, "operatorEmpjobid");
            return (Criteria) this;
        }

        public Criteria andOperatorEmpjobidNotEqualTo(String value) {
            addCriterion("operator_empJobId <>", value, "operatorEmpjobid");
            return (Criteria) this;
        }

        public Criteria andOperatorEmpjobidGreaterThan(String value) {
            addCriterion("operator_empJobId >", value, "operatorEmpjobid");
            return (Criteria) this;
        }

        public Criteria andOperatorEmpjobidGreaterThanOrEqualTo(String value) {
            addCriterion("operator_empJobId >=", value, "operatorEmpjobid");
            return (Criteria) this;
        }

        public Criteria andOperatorEmpjobidLessThan(String value) {
            addCriterion("operator_empJobId <", value, "operatorEmpjobid");
            return (Criteria) this;
        }

        public Criteria andOperatorEmpjobidLessThanOrEqualTo(String value) {
            addCriterion("operator_empJobId <=", value, "operatorEmpjobid");
            return (Criteria) this;
        }

        public Criteria andOperatorEmpjobidLike(String value) {
            addCriterion("operator_empJobId like", value, "operatorEmpjobid");
            return (Criteria) this;
        }

        public Criteria andOperatorEmpjobidNotLike(String value) {
            addCriterion("operator_empJobId not like", value, "operatorEmpjobid");
            return (Criteria) this;
        }

        public Criteria andOperatorEmpjobidIn(List<String> values) {
            addCriterion("operator_empJobId in", values, "operatorEmpjobid");
            return (Criteria) this;
        }

        public Criteria andOperatorEmpjobidNotIn(List<String> values) {
            addCriterion("operator_empJobId not in", values, "operatorEmpjobid");
            return (Criteria) this;
        }

        public Criteria andOperatorEmpjobidBetween(String value1, String value2) {
            addCriterion("operator_empJobId between", value1, value2, "operatorEmpjobid");
            return (Criteria) this;
        }

        public Criteria andOperatorEmpjobidNotBetween(String value1, String value2) {
            addCriterion("operator_empJobId not between", value1, value2, "operatorEmpjobid");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table attendance_time
     *
     * @mbg.generated do_not_delete_during_merge Mon May 25 19:32:58 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table attendance_time
     *
     * @mbg.generated Mon May 25 19:32:58 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}