package com.lqs.hrm.entity;

/**
 * 部门实体类
 * @author Administrator
 *
 */
public class Department {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column department.dept_id
     *
     * @mbg.generated Fri Mar 27 08:53:58 CST 2020
     */
    private Integer deptId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column department.dept_name
     *
     * @mbg.generated Fri Mar 27 08:53:58 CST 2020
     */
    private String deptName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column department.dept_level
     *
     * @mbg.generated Fri Mar 27 08:53:58 CST 2020
     */
    private Integer deptLevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column department.dept_desc
     *
     * @mbg.generated Fri Mar 27 08:53:58 CST 2020
     */
    private String deptDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column department.dept_empNum
     *
     * @mbg.generated Fri Mar 27 08:53:58 CST 2020
     */
    private Integer deptEmpnum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column department.status_id
     *
     * @mbg.generated Fri Mar 27 08:53:58 CST 2020
     */
    private Integer statusId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column department.parent_id
     *
     * @mbg.generated Fri Mar 27 08:53:58 CST 2020
     */
    private Integer parentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column department.manage_empJobId
     *
     * @mbg.generated Fri Mar 27 08:53:58 CST 2020
     */
    private Integer manageEmpjobid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department.dept_id
     *
     * @return the value of department.dept_id
     *
     * @mbg.generated Fri Mar 27 08:53:58 CST 2020
     */
    public Integer getDeptId() {
        return deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department.dept_id
     *
     * @param deptId the value for department.dept_id
     *
     * @mbg.generated Fri Mar 27 08:53:58 CST 2020
     */
    public void setDeptId(Integer deptId) {
        this.deptId = deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department.dept_name
     *
     * @return the value of department.dept_name
     *
     * @mbg.generated Fri Mar 27 08:53:58 CST 2020
     */
    public String getDeptName() {
        return deptName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department.dept_name
     *
     * @param deptName the value for department.dept_name
     *
     * @mbg.generated Fri Mar 27 08:53:58 CST 2020
     */
    public void setDeptName(String deptName) {
        this.deptName = deptName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department.dept_level
     *
     * @return the value of department.dept_level
     *
     * @mbg.generated Fri Mar 27 08:53:58 CST 2020
     */
    public Integer getDeptLevel() {
        return deptLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department.dept_level
     *
     * @param deptLevel the value for department.dept_level
     *
     * @mbg.generated Fri Mar 27 08:53:58 CST 2020
     */
    public void setDeptLevel(Integer deptLevel) {
        this.deptLevel = deptLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department.dept_desc
     *
     * @return the value of department.dept_desc
     *
     * @mbg.generated Fri Mar 27 08:53:58 CST 2020
     */
    public String getDeptDesc() {
        return deptDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department.dept_desc
     *
     * @param deptDesc the value for department.dept_desc
     *
     * @mbg.generated Fri Mar 27 08:53:58 CST 2020
     */
    public void setDeptDesc(String deptDesc) {
        this.deptDesc = deptDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department.dept_empNum
     *
     * @return the value of department.dept_empNum
     *
     * @mbg.generated Fri Mar 27 08:53:58 CST 2020
     */
    public Integer getDeptEmpnum() {
        return deptEmpnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department.dept_empNum
     *
     * @param deptEmpnum the value for department.dept_empNum
     *
     * @mbg.generated Fri Mar 27 08:53:58 CST 2020
     */
    public void setDeptEmpnum(Integer deptEmpnum) {
        this.deptEmpnum = deptEmpnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department.status_id
     *
     * @return the value of department.status_id
     *
     * @mbg.generated Fri Mar 27 08:53:58 CST 2020
     */
    public Integer getStatusId() {
        return statusId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department.status_id
     *
     * @param statusId the value for department.status_id
     *
     * @mbg.generated Fri Mar 27 08:53:58 CST 2020
     */
    public void setStatusId(Integer statusId) {
        this.statusId = statusId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department.parent_id
     *
     * @return the value of department.parent_id
     *
     * @mbg.generated Fri Mar 27 08:53:58 CST 2020
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department.parent_id
     *
     * @param parentId the value for department.parent_id
     *
     * @mbg.generated Fri Mar 27 08:53:58 CST 2020
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department.manage_empJobId
     *
     * @return the value of department.manage_empJobId
     *
     * @mbg.generated Fri Mar 27 08:53:58 CST 2020
     */
    public Integer getManageEmpjobid() {
        return manageEmpjobid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department.manage_empJobId
     *
     * @param manageEmpjobid the value for department.manage_empJobId
     *
     * @mbg.generated Fri Mar 27 08:53:58 CST 2020
     */
    public void setManageEmpjobid(Integer manageEmpjobid) {
        this.manageEmpjobid = manageEmpjobid;
    }
}