package com.lqs.hrm.entity;

import java.util.Date;

/**
 * 部门级别实体类
 * @author Administrator
 *
 */
public class DepartmentLevel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column department_level.dl_id
     *
     * @mbg.generated Tue Mar 31 16:18:10 CST 2020
     */
    private Integer dlId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column department_level.level
     *
     * @mbg.generated Tue Mar 31 16:18:10 CST 2020
     */
    private Integer level;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column department_level.level_desc
     *
     * @mbg.generated Tue Mar 31 16:18:10 CST 2020
     */
    private String levelDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column department_level.operator_date
     *
     * @mbg.generated Tue Mar 31 16:18:10 CST 2020
     */
    private Date operatorDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column department_level.operator_empJobId
     *
     * @mbg.generated Tue Mar 31 16:18:10 CST 2020
     */
    private Integer operatorEmpjobid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department_level.dl_id
     *
     * @return the value of department_level.dl_id
     *
     * @mbg.generated Tue Mar 31 16:18:10 CST 2020
     */
    public Integer getDlId() {
        return dlId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department_level.dl_id
     *
     * @param dlId the value for department_level.dl_id
     *
     * @mbg.generated Tue Mar 31 16:18:10 CST 2020
     */
    public void setDlId(Integer dlId) {
        this.dlId = dlId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department_level.level
     *
     * @return the value of department_level.level
     *
     * @mbg.generated Tue Mar 31 16:18:10 CST 2020
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department_level.level
     *
     * @param level the value for department_level.level
     *
     * @mbg.generated Tue Mar 31 16:18:10 CST 2020
     */
    public void setLevel(Integer level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department_level.level_desc
     *
     * @return the value of department_level.level_desc
     *
     * @mbg.generated Tue Mar 31 16:18:10 CST 2020
     */
    public String getLevelDesc() {
        return levelDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department_level.level_desc
     *
     * @param levelDesc the value for department_level.level_desc
     *
     * @mbg.generated Tue Mar 31 16:18:10 CST 2020
     */
    public void setLevelDesc(String levelDesc) {
        this.levelDesc = levelDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department_level.operator_date
     *
     * @return the value of department_level.operator_date
     *
     * @mbg.generated Tue Mar 31 16:18:10 CST 2020
     */
    public Date getOperatorDate() {
        return operatorDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department_level.operator_date
     *
     * @param operatorDate the value for department_level.operator_date
     *
     * @mbg.generated Tue Mar 31 16:18:10 CST 2020
     */
    public void setOperatorDate(Date operatorDate) {
        this.operatorDate = operatorDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department_level.operator_empJobId
     *
     * @return the value of department_level.operator_empJobId
     *
     * @mbg.generated Tue Mar 31 16:18:10 CST 2020
     */
    public Integer getOperatorEmpjobid() {
        return operatorEmpjobid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department_level.operator_empJobId
     *
     * @param operatorEmpjobid the value for department_level.operator_empJobId
     *
     * @mbg.generated Tue Mar 31 16:18:10 CST 2020
     */
    public void setOperatorEmpjobid(Integer operatorEmpjobid) {
        this.operatorEmpjobid = operatorEmpjobid;
    }
}