package com.lqs.hrm.entity;

import java.util.Date;


/**
 * 部门实体类
 * @author luckyliuqs
 *
 */
public class Department {
    /**
     * 部门ID
	 * This field was generated by MyBatis Generator. This field corresponds to the database column department.dept_id
	 * @mbg.generated  Mon May 25 00:12:47 CST 2020
	 */
	private Integer deptId;

	/**
	 * 部门名称
	 * This field was generated by MyBatis Generator. This field corresponds to the database column department.dept_name
	 * @mbg.generated  Mon May 25 00:12:47 CST 2020
	 */
	private String deptName;

	/**
	 * 部门描述
	 * This field was generated by MyBatis Generator. This field corresponds to the database column department.dept_desc
	 * @mbg.generated  Mon May 25 00:12:47 CST 2020
	 */
	private String deptDesc;

	/**
	 * 部门级别ID
	 * This field was generated by MyBatis Generator. This field corresponds to the database column department.dl_id
	 * @mbg.generated  Mon May 25 00:12:47 CST 2020
	 */
	private Integer dlId;

	/**
	 * 部门职工数量
	 * This field was generated by MyBatis Generator. This field corresponds to the database column department.dept_empNum
	 * @mbg.generated  Mon May 25 00:12:47 CST 2020
	 */
	private Integer deptEmpnum;

	/**
	 * 部门状态ID
	 * This field was generated by MyBatis Generator. This field corresponds to the database column department.status_id
	 * @mbg.generated  Mon May 25 00:12:47 CST 2020
	 */
	private Integer statusId;

	/**
	 * 上级部门ID
	 * This field was generated by MyBatis Generator. This field corresponds to the database column department.parent_id
	 * @mbg.generated  Mon May 25 00:12:47 CST 2020
	 */
	private Integer parentId;

	/**
	 * 部门主管职位ID
	 * This field was generated by MyBatis Generator. This field corresponds to the database column department.manage_positionId
	 * @mbg.generated  Mon May 25 00:12:47 CST 2020
	 */
	private Integer managePositionid;

	/**
	 * 最后一次操作时间
	 * This field was generated by MyBatis Generator. This field corresponds to the database column department.last_operator_date
	 * @mbg.generated  Mon May 25 00:12:47 CST 2020
	 */
	private Date lastOperatorDate;

	/**
	 * 操作人工号
	 * This field was generated by MyBatis Generator. This field corresponds to the database column department.operator_empJobId
	 * @mbg.generated  Mon May 25 00:12:47 CST 2020
	 */
	private String operatorEmpjobid;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column department.dept_id
	 * @return  the value of department.dept_id
	 * @mbg.generated  Mon May 25 00:12:47 CST 2020
	 */
	public Integer getDeptId() {
		return deptId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column department.dept_id
	 * @param deptId  the value for department.dept_id
	 * @mbg.generated  Mon May 25 00:12:47 CST 2020
	 */
	public void setDeptId(Integer deptId) {
		this.deptId = deptId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column department.dept_name
	 * @return  the value of department.dept_name
	 * @mbg.generated  Mon May 25 00:12:47 CST 2020
	 */
	public String getDeptName() {
		return deptName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column department.dept_name
	 * @param deptName  the value for department.dept_name
	 * @mbg.generated  Mon May 25 00:12:47 CST 2020
	 */
	public void setDeptName(String deptName) {
		this.deptName = deptName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column department.dept_desc
	 * @return  the value of department.dept_desc
	 * @mbg.generated  Mon May 25 00:12:47 CST 2020
	 */
	public String getDeptDesc() {
		return deptDesc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column department.dept_desc
	 * @param deptDesc  the value for department.dept_desc
	 * @mbg.generated  Mon May 25 00:12:47 CST 2020
	 */
	public void setDeptDesc(String deptDesc) {
		this.deptDesc = deptDesc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column department.dl_id
	 * @return  the value of department.dl_id
	 * @mbg.generated  Mon May 25 00:12:47 CST 2020
	 */
	public Integer getDlId() {
		return dlId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column department.dl_id
	 * @param dlId  the value for department.dl_id
	 * @mbg.generated  Mon May 25 00:12:47 CST 2020
	 */
	public void setDlId(Integer dlId) {
		this.dlId = dlId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column department.dept_empNum
	 * @return  the value of department.dept_empNum
	 * @mbg.generated  Mon May 25 00:12:47 CST 2020
	 */
	public Integer getDeptEmpnum() {
		return deptEmpnum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column department.dept_empNum
	 * @param deptEmpnum  the value for department.dept_empNum
	 * @mbg.generated  Mon May 25 00:12:47 CST 2020
	 */
	public void setDeptEmpnum(Integer deptEmpnum) {
		this.deptEmpnum = deptEmpnum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column department.status_id
	 * @return  the value of department.status_id
	 * @mbg.generated  Mon May 25 00:12:47 CST 2020
	 */
	public Integer getStatusId() {
		return statusId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column department.status_id
	 * @param statusId  the value for department.status_id
	 * @mbg.generated  Mon May 25 00:12:47 CST 2020
	 */
	public void setStatusId(Integer statusId) {
		this.statusId = statusId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column department.parent_id
	 * @return  the value of department.parent_id
	 * @mbg.generated  Mon May 25 00:12:47 CST 2020
	 */
	public Integer getParentId() {
		return parentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column department.parent_id
	 * @param parentId  the value for department.parent_id
	 * @mbg.generated  Mon May 25 00:12:47 CST 2020
	 */
	public void setParentId(Integer parentId) {
		this.parentId = parentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column department.manage_positionId
	 * @return  the value of department.manage_positionId
	 * @mbg.generated  Mon May 25 00:12:47 CST 2020
	 */
	public Integer getManagePositionid() {
		return managePositionid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column department.manage_positionId
	 * @param managePositionid  the value for department.manage_positionId
	 * @mbg.generated  Mon May 25 00:12:47 CST 2020
	 */
	public void setManagePositionid(Integer managePositionid) {
		this.managePositionid = managePositionid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column department.last_operator_date
	 * @return  the value of department.last_operator_date
	 * @mbg.generated  Mon May 25 00:12:47 CST 2020
	 */
	public Date getLastOperatorDate() {
		return lastOperatorDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column department.last_operator_date
	 * @param lastOperatorDate  the value for department.last_operator_date
	 * @mbg.generated  Mon May 25 00:12:47 CST 2020
	 */
	public void setLastOperatorDate(Date lastOperatorDate) {
		this.lastOperatorDate = lastOperatorDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column department.operator_empJobId
	 * @return  the value of department.operator_empJobId
	 * @mbg.generated  Mon May 25 00:12:47 CST 2020
	 */
	public String getOperatorEmpjobid() {
		return operatorEmpjobid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column department.operator_empJobId
	 * @param operatorEmpjobid  the value for department.operator_empJobId
	 * @mbg.generated  Mon May 25 00:12:47 CST 2020
	 */
	public void setOperatorEmpjobid(String operatorEmpjobid) {
		this.operatorEmpjobid = operatorEmpjobid;
	}

	/**
     * 部门级别
     */
    private Integer dlLeve;

    /**
     * 状态名称
     */
    private String statusName = "";

    /**
     * 上级部门名称
     */
    private String parentDeptName = "";

    /**
     * 部门主管职位名称
     */
    private String managePositionName = "";
    
    /**
     * 部门主管人工号
     */
    private String manageEmpJobId = "";
    
    /**
     * 部门主管人名称
     */
    private String manageEmpName = "";

    /**
     * 操作人名称
     */
    private String operatorEmpName = "";
    
    public Integer getDlLeve() {
		return dlLeve;
	}

	public void setDlLeve(Integer dlLeve) {
		this.dlLeve = dlLeve;
	}

	public String getStatusName() {
		return statusName;
	}

	public void setStatusName(String statusName) {
		this.statusName = statusName;
	}

	public String getParentDeptName() {
		return parentDeptName;
	}

	public void setParentDeptName(String parentDeptName) {
		this.parentDeptName = parentDeptName;
	}

	public String getManagePositionName() {
		return managePositionName;
	}

	public void setManagePositionName(String managePositionName) {
		this.managePositionName = managePositionName;
	}

	public String getOperatorEmpName() {
		return operatorEmpName;
	}

	public void setOperatorEmpName(String operatorEmpName) {
		this.operatorEmpName = operatorEmpName;
	}

	public String getManageEmpName() {
		return manageEmpName;
	}

	public void setManageEmpName(String manageEmpName) {
		this.manageEmpName = manageEmpName;
	}

	public String getManageEmpJobId() {
		return manageEmpJobId;
	}

	public void setManageEmpJobId(String manageEmpJobId) {
		this.manageEmpJobId = manageEmpJobId;
	}

}