package com.lqs.hrm.entity;

import java.util.Date;
import java.util.List;

/**
 * 职工实体咧
 * @author luckyliuqs
 *
 */
public class Employee {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.emp_jobId
     *
     * @mbg.generated Sat May 23 19:12:42 CST 2020
     */
    private String empJobid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.emp_name
     *
     * @mbg.generated Sat May 23 19:12:42 CST 2020
     */
    private String empName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.emp_sex
     *
     * @mbg.generated Sat May 23 19:12:42 CST 2020
     */
    private Integer empSex;
    
    /**
     * 职工性别名称
     */
    private String empSexName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.emp_birthday
     *
     * @mbg.generated Sat May 23 19:12:42 CST 2020
     */
    private String empBirthday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.emp_IDCard
     *
     * @mbg.generated Sat May 23 19:12:42 CST 2020
     */
    private String empIdcard;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.emp_phone
     *
     * @mbg.generated Sat May 23 19:12:42 CST 2020
     */
    private String empPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.emp_email
     *
     * @mbg.generated Sat May 23 19:12:42 CST 2020
     */
    private String empEmail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.emp_education
     *
     * @mbg.generated Sat May 23 19:12:42 CST 2020
     */
    private String empEducation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.emp_address
     *
     * @mbg.generated Sat May 23 19:12:42 CST 2020
     */
    private String empAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.entry_time
     *
     * @mbg.generated Sat May 23 19:12:42 CST 2020
     */
    private Date entryTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.status_id
     *
     * @mbg.generated Sat May 23 19:12:42 CST 2020
     */
    private Integer statusId;
    
    /**
     * 职工所属状态名称
     */
    private String statusName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.emp_note
     *
     * @mbg.generated Sat May 23 19:12:42 CST 2020
     */
    private String empNote;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.last_operator_date
     *
     * @mbg.generated Sat May 23 19:12:42 CST 2020
     */
    private Date lastOperatorDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.operator_empJobId
     *
     * @mbg.generated Sat May 23 19:12:42 CST 2020
     */
    private String operatorEmpjobid;

    /**
     * 操作人姓名
     */
    private String operatorEmpName;

    /**
     * 职工所属部门List集合
     */
    private List<Department> departmentList;
    
    /**
     * 职工所属部门名称List集合的Str形式
     */
    private String deptNameListStr;
    
    /**
     * 职工所属职位id
     */
    private List<Position> positionList;
    
    /**
     * 职工所属部职位名称List集合的Str形式
     */
    private String positionNameListStr;
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.emp_jobId
     *
     * @return the value of employee.emp_jobId
     *
     * @mbg.generated Sat May 23 19:12:42 CST 2020
     */
    public String getEmpJobid() {
        return empJobid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.emp_jobId
     *
     * @param empJobid the value for employee.emp_jobId
     *
     * @mbg.generated Sat May 23 19:12:42 CST 2020
     */
    public void setEmpJobid(String empJobid) {
        this.empJobid = empJobid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.emp_name
     *
     * @return the value of employee.emp_name
     *
     * @mbg.generated Sat May 23 19:12:42 CST 2020
     */
    public String getEmpName() {
        return empName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.emp_name
     *
     * @param empName the value for employee.emp_name
     *
     * @mbg.generated Sat May 23 19:12:42 CST 2020
     */
    public void setEmpName(String empName) {
        this.empName = empName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.emp_sex
     *
     * @return the value of employee.emp_sex
     *
     * @mbg.generated Sat May 23 19:12:42 CST 2020
     */
    public Integer getEmpSex() {
        return empSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.emp_sex
     *
     * @param empSex the value for employee.emp_sex
     *
     * @mbg.generated Sat May 23 19:12:42 CST 2020
     */
    public void setEmpSex(Integer empSex) {
        this.empSex = empSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.emp_birthday
     *
     * @return the value of employee.emp_birthday
     *
     * @mbg.generated Sat May 23 19:12:42 CST 2020
     */
    public String getEmpBirthday() {
        return empBirthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.emp_birthday
     *
     * @param empBirthday the value for employee.emp_birthday
     *
     * @mbg.generated Sat May 23 19:12:42 CST 2020
     */
    public void setEmpBirthday(String empBirthday) {
        this.empBirthday = empBirthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.emp_IDCard
     *
     * @return the value of employee.emp_IDCard
     *
     * @mbg.generated Sat May 23 19:12:42 CST 2020
     */
    public String getEmpIdcard() {
        return empIdcard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.emp_IDCard
     *
     * @param empIdcard the value for employee.emp_IDCard
     *
     * @mbg.generated Sat May 23 19:12:42 CST 2020
     */
    public void setEmpIdcard(String empIdcard) {
        this.empIdcard = empIdcard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.emp_phone
     *
     * @return the value of employee.emp_phone
     *
     * @mbg.generated Sat May 23 19:12:42 CST 2020
     */
    public String getEmpPhone() {
        return empPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.emp_phone
     *
     * @param empPhone the value for employee.emp_phone
     *
     * @mbg.generated Sat May 23 19:12:42 CST 2020
     */
    public void setEmpPhone(String empPhone) {
        this.empPhone = empPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.emp_email
     *
     * @return the value of employee.emp_email
     *
     * @mbg.generated Sat May 23 19:12:42 CST 2020
     */
    public String getEmpEmail() {
        return empEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.emp_email
     *
     * @param empEmail the value for employee.emp_email
     *
     * @mbg.generated Sat May 23 19:12:42 CST 2020
     */
    public void setEmpEmail(String empEmail) {
        this.empEmail = empEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.emp_education
     *
     * @return the value of employee.emp_education
     *
     * @mbg.generated Sat May 23 19:12:42 CST 2020
     */
    public String getEmpEducation() {
        return empEducation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.emp_education
     *
     * @param empEducation the value for employee.emp_education
     *
     * @mbg.generated Sat May 23 19:12:42 CST 2020
     */
    public void setEmpEducation(String empEducation) {
        this.empEducation = empEducation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.emp_address
     *
     * @return the value of employee.emp_address
     *
     * @mbg.generated Sat May 23 19:12:42 CST 2020
     */
    public String getEmpAddress() {
        return empAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.emp_address
     *
     * @param empAddress the value for employee.emp_address
     *
     * @mbg.generated Sat May 23 19:12:42 CST 2020
     */
    public void setEmpAddress(String empAddress) {
        this.empAddress = empAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.entry_time
     *
     * @return the value of employee.entry_time
     *
     * @mbg.generated Sat May 23 19:12:42 CST 2020
     */
    public Date getEntryTime() {
        return entryTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.entry_time
     *
     * @param entryTime the value for employee.entry_time
     *
     * @mbg.generated Sat May 23 19:12:42 CST 2020
     */
    public void setEntryTime(Date entryTime) {
        this.entryTime = entryTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.status_id
     *
     * @return the value of employee.status_id
     *
     * @mbg.generated Sat May 23 19:12:42 CST 2020
     */
    public Integer getStatusId() {
        return statusId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.status_id
     *
     * @param statusId the value for employee.status_id
     *
     * @mbg.generated Sat May 23 19:12:42 CST 2020
     */
    public void setStatusId(Integer statusId) {
        this.statusId = statusId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.emp_note
     *
     * @return the value of employee.emp_note
     *
     * @mbg.generated Sat May 23 19:12:42 CST 2020
     */
    public String getEmpNote() {
        return empNote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.emp_note
     *
     * @param empNote the value for employee.emp_note
     *
     * @mbg.generated Sat May 23 19:12:42 CST 2020
     */
    public void setEmpNote(String empNote) {
        this.empNote = empNote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.last_operator_date
     *
     * @return the value of employee.last_operator_date
     *
     * @mbg.generated Sat May 23 19:12:42 CST 2020
     */
    public Date getLastOperatorDate() {
        return lastOperatorDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.last_operator_date
     *
     * @param lastOperatorDate the value for employee.last_operator_date
     *
     * @mbg.generated Sat May 23 19:12:42 CST 2020
     */
    public void setLastOperatorDate(Date lastOperatorDate) {
        this.lastOperatorDate = lastOperatorDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.operator_empJobId
     *
     * @return the value of employee.operator_empJobId
     *
     * @mbg.generated Sat May 23 19:12:42 CST 2020
     */
    public String getOperatorEmpjobid() {
        return operatorEmpjobid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.operator_empJobId
     *
     * @param operatorEmpjobid the value for employee.operator_empJobId
     *
     * @mbg.generated Sat May 23 19:12:42 CST 2020
     */
    public void setOperatorEmpjobid(String operatorEmpjobid) {
        this.operatorEmpjobid = operatorEmpjobid;
    }

	public String getEmpSexName() {
		return empSexName;
	}

	public void setEmpSexName(String empSexName) {
		this.empSexName = empSexName;
	}

	public String getStatusName() {
		return statusName;
	}

	public void setStatusName(String statusName) {
		this.statusName = statusName;
	}

	public String getOperatorEmpName() {
		return operatorEmpName;
	}

	public void setOperatorEmpName(String operatorEmpName) {
		this.operatorEmpName = operatorEmpName;
	}

	public String getDeptNameListStr() {
		return deptNameListStr;
	}

	public void setDeptNameListStr(String deptNameListStr) {
		this.deptNameListStr = deptNameListStr;
	}


	public List<Department> getDepartmentList() {
		return departmentList;
	}

	public void setDepartmentList(List<Department> departmentList) {
		this.departmentList = departmentList;
	}

	public List<Position> getPositionList() {
		return positionList;
	}

	public void setPositionList(List<Position> positionList) {
		this.positionList = positionList;
	}

	public String getPositionNameListStr() {
		return positionNameListStr;
	}

	public void setPositionNameListStr(String positionNameListStr) {
		this.positionNameListStr = positionNameListStr;
	}
    
}
