package com.lqs.hrm.entity;

import java.util.Date;

/**
 * 职工入职实体类
 * @author luckyliuqs
 *
 */
public class EmployeeEntry {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_entry.ee_id
     *
     * @mbg.generated Wed May 20 00:13:03 CST 2020
     */
    private Integer eeId;

    /**
     * 当日入职数量
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_entry.entry_empNum
     *
     * @mbg.generated Wed May 20 00:13:03 CST 2020
     */
    private Integer entryEmpnum;

    /**
     * 入职日期
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_entry.entry_date
     *
     * @mbg.generated Wed May 20 00:13:03 CST 2020
     */
    private Date entryDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_entry.ee_id
     *
     * @return the value of employee_entry.ee_id
     *
     * @mbg.generated Wed May 20 00:13:03 CST 2020
     */
    public Integer getEeId() {
        return eeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_entry.ee_id
     *
     * @param eeId the value for employee_entry.ee_id
     *
     * @mbg.generated Wed May 20 00:13:03 CST 2020
     */
    public void setEeId(Integer eeId) {
        this.eeId = eeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_entry.entry_empNum
     *
     * @return the value of employee_entry.entry_empNum
     *
     * @mbg.generated Wed May 20 00:13:03 CST 2020
     */
    public Integer getEntryEmpnum() {
        return entryEmpnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_entry.entry_empNum
     *
     * @param entryEmpnum the value for employee_entry.entry_empNum
     *
     * @mbg.generated Wed May 20 00:13:03 CST 2020
     */
    public void setEntryEmpnum(Integer entryEmpnum) {
        this.entryEmpnum = entryEmpnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_entry.entry_date
     *
     * @return the value of employee_entry.entry_date
     *
     * @mbg.generated Wed May 20 00:13:03 CST 2020
     */
    public Date getEntryDate() {
        return entryDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_entry.entry_date
     *
     * @param entryDate the value for employee_entry.entry_date
     *
     * @mbg.generated Wed May 20 00:13:03 CST 2020
     */
    public void setEntryDate(Date entryDate) {
        this.entryDate = entryDate;
    }
}