package com.lqs.hrm.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class EmployeeExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table employee
     *
     * @mbg.generated Sat Apr 04 14:05:24 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table employee
     *
     * @mbg.generated Sat Apr 04 14:05:24 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table employee
     *
     * @mbg.generated Sat Apr 04 14:05:24 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee
     *
     * @mbg.generated Sat Apr 04 14:05:24 CST 2020
     */
    public EmployeeExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee
     *
     * @mbg.generated Sat Apr 04 14:05:24 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee
     *
     * @mbg.generated Sat Apr 04 14:05:24 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee
     *
     * @mbg.generated Sat Apr 04 14:05:24 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee
     *
     * @mbg.generated Sat Apr 04 14:05:24 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee
     *
     * @mbg.generated Sat Apr 04 14:05:24 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee
     *
     * @mbg.generated Sat Apr 04 14:05:24 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee
     *
     * @mbg.generated Sat Apr 04 14:05:24 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee
     *
     * @mbg.generated Sat Apr 04 14:05:24 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee
     *
     * @mbg.generated Sat Apr 04 14:05:24 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee
     *
     * @mbg.generated Sat Apr 04 14:05:24 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table employee
     *
     * @mbg.generated Sat Apr 04 14:05:24 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andEmpJobidIsNull() {
            addCriterion("emp_jobId is null");
            return (Criteria) this;
        }

        public Criteria andEmpJobidIsNotNull() {
            addCriterion("emp_jobId is not null");
            return (Criteria) this;
        }

        public Criteria andEmpJobidEqualTo(String value) {
            addCriterion("emp_jobId =", value, "empJobid");
            return (Criteria) this;
        }

        public Criteria andEmpJobidNotEqualTo(String value) {
            addCriterion("emp_jobId <>", value, "empJobid");
            return (Criteria) this;
        }

        public Criteria andEmpJobidGreaterThan(String value) {
            addCriterion("emp_jobId >", value, "empJobid");
            return (Criteria) this;
        }

        public Criteria andEmpJobidGreaterThanOrEqualTo(String value) {
            addCriterion("emp_jobId >=", value, "empJobid");
            return (Criteria) this;
        }

        public Criteria andEmpJobidLessThan(String value) {
            addCriterion("emp_jobId <", value, "empJobid");
            return (Criteria) this;
        }

        public Criteria andEmpJobidLessThanOrEqualTo(String value) {
            addCriterion("emp_jobId <=", value, "empJobid");
            return (Criteria) this;
        }

        public Criteria andEmpJobidLike(String value) {
            addCriterion("emp_jobId like", value, "empJobid");
            return (Criteria) this;
        }

        public Criteria andEmpJobidNotLike(String value) {
            addCriterion("emp_jobId not like", value, "empJobid");
            return (Criteria) this;
        }

        public Criteria andEmpJobidIn(List<String> values) {
            addCriterion("emp_jobId in", values, "empJobid");
            return (Criteria) this;
        }

        public Criteria andEmpJobidNotIn(List<String> values) {
            addCriterion("emp_jobId not in", values, "empJobid");
            return (Criteria) this;
        }

        public Criteria andEmpJobidBetween(String value1, String value2) {
            addCriterion("emp_jobId between", value1, value2, "empJobid");
            return (Criteria) this;
        }

        public Criteria andEmpJobidNotBetween(String value1, String value2) {
            addCriterion("emp_jobId not between", value1, value2, "empJobid");
            return (Criteria) this;
        }

        public Criteria andEmpNameIsNull() {
            addCriterion("emp_name is null");
            return (Criteria) this;
        }

        public Criteria andEmpNameIsNotNull() {
            addCriterion("emp_name is not null");
            return (Criteria) this;
        }

        public Criteria andEmpNameEqualTo(String value) {
            addCriterion("emp_name =", value, "empName");
            return (Criteria) this;
        }

        public Criteria andEmpNameNotEqualTo(String value) {
            addCriterion("emp_name <>", value, "empName");
            return (Criteria) this;
        }

        public Criteria andEmpNameGreaterThan(String value) {
            addCriterion("emp_name >", value, "empName");
            return (Criteria) this;
        }

        public Criteria andEmpNameGreaterThanOrEqualTo(String value) {
            addCriterion("emp_name >=", value, "empName");
            return (Criteria) this;
        }

        public Criteria andEmpNameLessThan(String value) {
            addCriterion("emp_name <", value, "empName");
            return (Criteria) this;
        }

        public Criteria andEmpNameLessThanOrEqualTo(String value) {
            addCriterion("emp_name <=", value, "empName");
            return (Criteria) this;
        }

        public Criteria andEmpNameLike(String value) {
            addCriterion("emp_name like", value, "empName");
            return (Criteria) this;
        }

        public Criteria andEmpNameNotLike(String value) {
            addCriterion("emp_name not like", value, "empName");
            return (Criteria) this;
        }

        public Criteria andEmpNameIn(List<String> values) {
            addCriterion("emp_name in", values, "empName");
            return (Criteria) this;
        }

        public Criteria andEmpNameNotIn(List<String> values) {
            addCriterion("emp_name not in", values, "empName");
            return (Criteria) this;
        }

        public Criteria andEmpNameBetween(String value1, String value2) {
            addCriterion("emp_name between", value1, value2, "empName");
            return (Criteria) this;
        }

        public Criteria andEmpNameNotBetween(String value1, String value2) {
            addCriterion("emp_name not between", value1, value2, "empName");
            return (Criteria) this;
        }

        public Criteria andEmpSexIsNull() {
            addCriterion("emp_sex is null");
            return (Criteria) this;
        }

        public Criteria andEmpSexIsNotNull() {
            addCriterion("emp_sex is not null");
            return (Criteria) this;
        }

        public Criteria andEmpSexEqualTo(Integer value) {
            addCriterion("emp_sex =", value, "empSex");
            return (Criteria) this;
        }

        public Criteria andEmpSexNotEqualTo(Integer value) {
            addCriterion("emp_sex <>", value, "empSex");
            return (Criteria) this;
        }

        public Criteria andEmpSexGreaterThan(Integer value) {
            addCriterion("emp_sex >", value, "empSex");
            return (Criteria) this;
        }

        public Criteria andEmpSexGreaterThanOrEqualTo(Integer value) {
            addCriterion("emp_sex >=", value, "empSex");
            return (Criteria) this;
        }

        public Criteria andEmpSexLessThan(Integer value) {
            addCriterion("emp_sex <", value, "empSex");
            return (Criteria) this;
        }

        public Criteria andEmpSexLessThanOrEqualTo(Integer value) {
            addCriterion("emp_sex <=", value, "empSex");
            return (Criteria) this;
        }

        public Criteria andEmpSexIn(List<Integer> values) {
            addCriterion("emp_sex in", values, "empSex");
            return (Criteria) this;
        }

        public Criteria andEmpSexNotIn(List<Integer> values) {
            addCriterion("emp_sex not in", values, "empSex");
            return (Criteria) this;
        }

        public Criteria andEmpSexBetween(Integer value1, Integer value2) {
            addCriterion("emp_sex between", value1, value2, "empSex");
            return (Criteria) this;
        }

        public Criteria andEmpSexNotBetween(Integer value1, Integer value2) {
            addCriterion("emp_sex not between", value1, value2, "empSex");
            return (Criteria) this;
        }

        public Criteria andEmpBirthdayIsNull() {
            addCriterion("emp_birthday is null");
            return (Criteria) this;
        }

        public Criteria andEmpBirthdayIsNotNull() {
            addCriterion("emp_birthday is not null");
            return (Criteria) this;
        }

        public Criteria andEmpBirthdayEqualTo(Date value) {
            addCriterionForJDBCDate("emp_birthday =", value, "empBirthday");
            return (Criteria) this;
        }

        public Criteria andEmpBirthdayNotEqualTo(Date value) {
            addCriterionForJDBCDate("emp_birthday <>", value, "empBirthday");
            return (Criteria) this;
        }

        public Criteria andEmpBirthdayGreaterThan(Date value) {
            addCriterionForJDBCDate("emp_birthday >", value, "empBirthday");
            return (Criteria) this;
        }

        public Criteria andEmpBirthdayGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("emp_birthday >=", value, "empBirthday");
            return (Criteria) this;
        }

        public Criteria andEmpBirthdayLessThan(Date value) {
            addCriterionForJDBCDate("emp_birthday <", value, "empBirthday");
            return (Criteria) this;
        }

        public Criteria andEmpBirthdayLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("emp_birthday <=", value, "empBirthday");
            return (Criteria) this;
        }

        public Criteria andEmpBirthdayIn(List<Date> values) {
            addCriterionForJDBCDate("emp_birthday in", values, "empBirthday");
            return (Criteria) this;
        }

        public Criteria andEmpBirthdayNotIn(List<Date> values) {
            addCriterionForJDBCDate("emp_birthday not in", values, "empBirthday");
            return (Criteria) this;
        }

        public Criteria andEmpBirthdayBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("emp_birthday between", value1, value2, "empBirthday");
            return (Criteria) this;
        }

        public Criteria andEmpBirthdayNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("emp_birthday not between", value1, value2, "empBirthday");
            return (Criteria) this;
        }

        public Criteria andEmpIdcardIsNull() {
            addCriterion("emp_IDCard is null");
            return (Criteria) this;
        }

        public Criteria andEmpIdcardIsNotNull() {
            addCriterion("emp_IDCard is not null");
            return (Criteria) this;
        }

        public Criteria andEmpIdcardEqualTo(String value) {
            addCriterion("emp_IDCard =", value, "empIdcard");
            return (Criteria) this;
        }

        public Criteria andEmpIdcardNotEqualTo(String value) {
            addCriterion("emp_IDCard <>", value, "empIdcard");
            return (Criteria) this;
        }

        public Criteria andEmpIdcardGreaterThan(String value) {
            addCriterion("emp_IDCard >", value, "empIdcard");
            return (Criteria) this;
        }

        public Criteria andEmpIdcardGreaterThanOrEqualTo(String value) {
            addCriterion("emp_IDCard >=", value, "empIdcard");
            return (Criteria) this;
        }

        public Criteria andEmpIdcardLessThan(String value) {
            addCriterion("emp_IDCard <", value, "empIdcard");
            return (Criteria) this;
        }

        public Criteria andEmpIdcardLessThanOrEqualTo(String value) {
            addCriterion("emp_IDCard <=", value, "empIdcard");
            return (Criteria) this;
        }

        public Criteria andEmpIdcardLike(String value) {
            addCriterion("emp_IDCard like", value, "empIdcard");
            return (Criteria) this;
        }

        public Criteria andEmpIdcardNotLike(String value) {
            addCriterion("emp_IDCard not like", value, "empIdcard");
            return (Criteria) this;
        }

        public Criteria andEmpIdcardIn(List<String> values) {
            addCriterion("emp_IDCard in", values, "empIdcard");
            return (Criteria) this;
        }

        public Criteria andEmpIdcardNotIn(List<String> values) {
            addCriterion("emp_IDCard not in", values, "empIdcard");
            return (Criteria) this;
        }

        public Criteria andEmpIdcardBetween(String value1, String value2) {
            addCriterion("emp_IDCard between", value1, value2, "empIdcard");
            return (Criteria) this;
        }

        public Criteria andEmpIdcardNotBetween(String value1, String value2) {
            addCriterion("emp_IDCard not between", value1, value2, "empIdcard");
            return (Criteria) this;
        }

        public Criteria andEmpPhoneIsNull() {
            addCriterion("emp_phone is null");
            return (Criteria) this;
        }

        public Criteria andEmpPhoneIsNotNull() {
            addCriterion("emp_phone is not null");
            return (Criteria) this;
        }

        public Criteria andEmpPhoneEqualTo(String value) {
            addCriterion("emp_phone =", value, "empPhone");
            return (Criteria) this;
        }

        public Criteria andEmpPhoneNotEqualTo(String value) {
            addCriterion("emp_phone <>", value, "empPhone");
            return (Criteria) this;
        }

        public Criteria andEmpPhoneGreaterThan(String value) {
            addCriterion("emp_phone >", value, "empPhone");
            return (Criteria) this;
        }

        public Criteria andEmpPhoneGreaterThanOrEqualTo(String value) {
            addCriterion("emp_phone >=", value, "empPhone");
            return (Criteria) this;
        }

        public Criteria andEmpPhoneLessThan(String value) {
            addCriterion("emp_phone <", value, "empPhone");
            return (Criteria) this;
        }

        public Criteria andEmpPhoneLessThanOrEqualTo(String value) {
            addCriterion("emp_phone <=", value, "empPhone");
            return (Criteria) this;
        }

        public Criteria andEmpPhoneLike(String value) {
            addCriterion("emp_phone like", value, "empPhone");
            return (Criteria) this;
        }

        public Criteria andEmpPhoneNotLike(String value) {
            addCriterion("emp_phone not like", value, "empPhone");
            return (Criteria) this;
        }

        public Criteria andEmpPhoneIn(List<String> values) {
            addCriterion("emp_phone in", values, "empPhone");
            return (Criteria) this;
        }

        public Criteria andEmpPhoneNotIn(List<String> values) {
            addCriterion("emp_phone not in", values, "empPhone");
            return (Criteria) this;
        }

        public Criteria andEmpPhoneBetween(String value1, String value2) {
            addCriterion("emp_phone between", value1, value2, "empPhone");
            return (Criteria) this;
        }

        public Criteria andEmpPhoneNotBetween(String value1, String value2) {
            addCriterion("emp_phone not between", value1, value2, "empPhone");
            return (Criteria) this;
        }

        public Criteria andEmpEmailIsNull() {
            addCriterion("emp_email is null");
            return (Criteria) this;
        }

        public Criteria andEmpEmailIsNotNull() {
            addCriterion("emp_email is not null");
            return (Criteria) this;
        }

        public Criteria andEmpEmailEqualTo(String value) {
            addCriterion("emp_email =", value, "empEmail");
            return (Criteria) this;
        }

        public Criteria andEmpEmailNotEqualTo(String value) {
            addCriterion("emp_email <>", value, "empEmail");
            return (Criteria) this;
        }

        public Criteria andEmpEmailGreaterThan(String value) {
            addCriterion("emp_email >", value, "empEmail");
            return (Criteria) this;
        }

        public Criteria andEmpEmailGreaterThanOrEqualTo(String value) {
            addCriterion("emp_email >=", value, "empEmail");
            return (Criteria) this;
        }

        public Criteria andEmpEmailLessThan(String value) {
            addCriterion("emp_email <", value, "empEmail");
            return (Criteria) this;
        }

        public Criteria andEmpEmailLessThanOrEqualTo(String value) {
            addCriterion("emp_email <=", value, "empEmail");
            return (Criteria) this;
        }

        public Criteria andEmpEmailLike(String value) {
            addCriterion("emp_email like", value, "empEmail");
            return (Criteria) this;
        }

        public Criteria andEmpEmailNotLike(String value) {
            addCriterion("emp_email not like", value, "empEmail");
            return (Criteria) this;
        }

        public Criteria andEmpEmailIn(List<String> values) {
            addCriterion("emp_email in", values, "empEmail");
            return (Criteria) this;
        }

        public Criteria andEmpEmailNotIn(List<String> values) {
            addCriterion("emp_email not in", values, "empEmail");
            return (Criteria) this;
        }

        public Criteria andEmpEmailBetween(String value1, String value2) {
            addCriterion("emp_email between", value1, value2, "empEmail");
            return (Criteria) this;
        }

        public Criteria andEmpEmailNotBetween(String value1, String value2) {
            addCriterion("emp_email not between", value1, value2, "empEmail");
            return (Criteria) this;
        }

        public Criteria andEmpEducationIsNull() {
            addCriterion("emp_education is null");
            return (Criteria) this;
        }

        public Criteria andEmpEducationIsNotNull() {
            addCriterion("emp_education is not null");
            return (Criteria) this;
        }

        public Criteria andEmpEducationEqualTo(String value) {
            addCriterion("emp_education =", value, "empEducation");
            return (Criteria) this;
        }

        public Criteria andEmpEducationNotEqualTo(String value) {
            addCriterion("emp_education <>", value, "empEducation");
            return (Criteria) this;
        }

        public Criteria andEmpEducationGreaterThan(String value) {
            addCriterion("emp_education >", value, "empEducation");
            return (Criteria) this;
        }

        public Criteria andEmpEducationGreaterThanOrEqualTo(String value) {
            addCriterion("emp_education >=", value, "empEducation");
            return (Criteria) this;
        }

        public Criteria andEmpEducationLessThan(String value) {
            addCriterion("emp_education <", value, "empEducation");
            return (Criteria) this;
        }

        public Criteria andEmpEducationLessThanOrEqualTo(String value) {
            addCriterion("emp_education <=", value, "empEducation");
            return (Criteria) this;
        }

        public Criteria andEmpEducationLike(String value) {
            addCriterion("emp_education like", value, "empEducation");
            return (Criteria) this;
        }

        public Criteria andEmpEducationNotLike(String value) {
            addCriterion("emp_education not like", value, "empEducation");
            return (Criteria) this;
        }

        public Criteria andEmpEducationIn(List<String> values) {
            addCriterion("emp_education in", values, "empEducation");
            return (Criteria) this;
        }

        public Criteria andEmpEducationNotIn(List<String> values) {
            addCriterion("emp_education not in", values, "empEducation");
            return (Criteria) this;
        }

        public Criteria andEmpEducationBetween(String value1, String value2) {
            addCriterion("emp_education between", value1, value2, "empEducation");
            return (Criteria) this;
        }

        public Criteria andEmpEducationNotBetween(String value1, String value2) {
            addCriterion("emp_education not between", value1, value2, "empEducation");
            return (Criteria) this;
        }

        public Criteria andEmpAddressIsNull() {
            addCriterion("emp_address is null");
            return (Criteria) this;
        }

        public Criteria andEmpAddressIsNotNull() {
            addCriterion("emp_address is not null");
            return (Criteria) this;
        }

        public Criteria andEmpAddressEqualTo(String value) {
            addCriterion("emp_address =", value, "empAddress");
            return (Criteria) this;
        }

        public Criteria andEmpAddressNotEqualTo(String value) {
            addCriterion("emp_address <>", value, "empAddress");
            return (Criteria) this;
        }

        public Criteria andEmpAddressGreaterThan(String value) {
            addCriterion("emp_address >", value, "empAddress");
            return (Criteria) this;
        }

        public Criteria andEmpAddressGreaterThanOrEqualTo(String value) {
            addCriterion("emp_address >=", value, "empAddress");
            return (Criteria) this;
        }

        public Criteria andEmpAddressLessThan(String value) {
            addCriterion("emp_address <", value, "empAddress");
            return (Criteria) this;
        }

        public Criteria andEmpAddressLessThanOrEqualTo(String value) {
            addCriterion("emp_address <=", value, "empAddress");
            return (Criteria) this;
        }

        public Criteria andEmpAddressLike(String value) {
            addCriterion("emp_address like", value, "empAddress");
            return (Criteria) this;
        }

        public Criteria andEmpAddressNotLike(String value) {
            addCriterion("emp_address not like", value, "empAddress");
            return (Criteria) this;
        }

        public Criteria andEmpAddressIn(List<String> values) {
            addCriterion("emp_address in", values, "empAddress");
            return (Criteria) this;
        }

        public Criteria andEmpAddressNotIn(List<String> values) {
            addCriterion("emp_address not in", values, "empAddress");
            return (Criteria) this;
        }

        public Criteria andEmpAddressBetween(String value1, String value2) {
            addCriterion("emp_address between", value1, value2, "empAddress");
            return (Criteria) this;
        }

        public Criteria andEmpAddressNotBetween(String value1, String value2) {
            addCriterion("emp_address not between", value1, value2, "empAddress");
            return (Criteria) this;
        }

        public Criteria andDeptIdIsNull() {
            addCriterion("dept_id is null");
            return (Criteria) this;
        }

        public Criteria andDeptIdIsNotNull() {
            addCriterion("dept_id is not null");
            return (Criteria) this;
        }

        public Criteria andDeptIdEqualTo(Integer value) {
            addCriterion("dept_id =", value, "deptId");
            return (Criteria) this;
        }

        public Criteria andDeptIdNotEqualTo(Integer value) {
            addCriterion("dept_id <>", value, "deptId");
            return (Criteria) this;
        }

        public Criteria andDeptIdGreaterThan(Integer value) {
            addCriterion("dept_id >", value, "deptId");
            return (Criteria) this;
        }

        public Criteria andDeptIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("dept_id >=", value, "deptId");
            return (Criteria) this;
        }

        public Criteria andDeptIdLessThan(Integer value) {
            addCriterion("dept_id <", value, "deptId");
            return (Criteria) this;
        }

        public Criteria andDeptIdLessThanOrEqualTo(Integer value) {
            addCriterion("dept_id <=", value, "deptId");
            return (Criteria) this;
        }

        public Criteria andDeptIdIn(List<Integer> values) {
            addCriterion("dept_id in", values, "deptId");
            return (Criteria) this;
        }

        public Criteria andDeptIdNotIn(List<Integer> values) {
            addCriterion("dept_id not in", values, "deptId");
            return (Criteria) this;
        }

        public Criteria andDeptIdBetween(Integer value1, Integer value2) {
            addCriterion("dept_id between", value1, value2, "deptId");
            return (Criteria) this;
        }

        public Criteria andDeptIdNotBetween(Integer value1, Integer value2) {
            addCriterion("dept_id not between", value1, value2, "deptId");
            return (Criteria) this;
        }

        public Criteria andPositionIdIsNull() {
            addCriterion("position_id is null");
            return (Criteria) this;
        }

        public Criteria andPositionIdIsNotNull() {
            addCriterion("position_id is not null");
            return (Criteria) this;
        }

        public Criteria andPositionIdEqualTo(Integer value) {
            addCriterion("position_id =", value, "positionId");
            return (Criteria) this;
        }

        public Criteria andPositionIdNotEqualTo(Integer value) {
            addCriterion("position_id <>", value, "positionId");
            return (Criteria) this;
        }

        public Criteria andPositionIdGreaterThan(Integer value) {
            addCriterion("position_id >", value, "positionId");
            return (Criteria) this;
        }

        public Criteria andPositionIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("position_id >=", value, "positionId");
            return (Criteria) this;
        }

        public Criteria andPositionIdLessThan(Integer value) {
            addCriterion("position_id <", value, "positionId");
            return (Criteria) this;
        }

        public Criteria andPositionIdLessThanOrEqualTo(Integer value) {
            addCriterion("position_id <=", value, "positionId");
            return (Criteria) this;
        }

        public Criteria andPositionIdIn(List<Integer> values) {
            addCriterion("position_id in", values, "positionId");
            return (Criteria) this;
        }

        public Criteria andPositionIdNotIn(List<Integer> values) {
            addCriterion("position_id not in", values, "positionId");
            return (Criteria) this;
        }

        public Criteria andPositionIdBetween(Integer value1, Integer value2) {
            addCriterion("position_id between", value1, value2, "positionId");
            return (Criteria) this;
        }

        public Criteria andPositionIdNotBetween(Integer value1, Integer value2) {
            addCriterion("position_id not between", value1, value2, "positionId");
            return (Criteria) this;
        }

        public Criteria andEntryTimeIsNull() {
            addCriterion("entry_time is null");
            return (Criteria) this;
        }

        public Criteria andEntryTimeIsNotNull() {
            addCriterion("entry_time is not null");
            return (Criteria) this;
        }

        public Criteria andEntryTimeEqualTo(Date value) {
            addCriterion("entry_time =", value, "entryTime");
            return (Criteria) this;
        }

        public Criteria andEntryTimeNotEqualTo(Date value) {
            addCriterion("entry_time <>", value, "entryTime");
            return (Criteria) this;
        }

        public Criteria andEntryTimeGreaterThan(Date value) {
            addCriterion("entry_time >", value, "entryTime");
            return (Criteria) this;
        }

        public Criteria andEntryTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("entry_time >=", value, "entryTime");
            return (Criteria) this;
        }

        public Criteria andEntryTimeLessThan(Date value) {
            addCriterion("entry_time <", value, "entryTime");
            return (Criteria) this;
        }

        public Criteria andEntryTimeLessThanOrEqualTo(Date value) {
            addCriterion("entry_time <=", value, "entryTime");
            return (Criteria) this;
        }

        public Criteria andEntryTimeIn(List<Date> values) {
            addCriterion("entry_time in", values, "entryTime");
            return (Criteria) this;
        }

        public Criteria andEntryTimeNotIn(List<Date> values) {
            addCriterion("entry_time not in", values, "entryTime");
            return (Criteria) this;
        }

        public Criteria andEntryTimeBetween(Date value1, Date value2) {
            addCriterion("entry_time between", value1, value2, "entryTime");
            return (Criteria) this;
        }

        public Criteria andEntryTimeNotBetween(Date value1, Date value2) {
            addCriterion("entry_time not between", value1, value2, "entryTime");
            return (Criteria) this;
        }

        public Criteria andStatusIdIsNull() {
            addCriterion("status_id is null");
            return (Criteria) this;
        }

        public Criteria andStatusIdIsNotNull() {
            addCriterion("status_id is not null");
            return (Criteria) this;
        }

        public Criteria andStatusIdEqualTo(Integer value) {
            addCriterion("status_id =", value, "statusId");
            return (Criteria) this;
        }

        public Criteria andStatusIdNotEqualTo(Integer value) {
            addCriterion("status_id <>", value, "statusId");
            return (Criteria) this;
        }

        public Criteria andStatusIdGreaterThan(Integer value) {
            addCriterion("status_id >", value, "statusId");
            return (Criteria) this;
        }

        public Criteria andStatusIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("status_id >=", value, "statusId");
            return (Criteria) this;
        }

        public Criteria andStatusIdLessThan(Integer value) {
            addCriterion("status_id <", value, "statusId");
            return (Criteria) this;
        }

        public Criteria andStatusIdLessThanOrEqualTo(Integer value) {
            addCriterion("status_id <=", value, "statusId");
            return (Criteria) this;
        }

        public Criteria andStatusIdIn(List<Integer> values) {
            addCriterion("status_id in", values, "statusId");
            return (Criteria) this;
        }

        public Criteria andStatusIdNotIn(List<Integer> values) {
            addCriterion("status_id not in", values, "statusId");
            return (Criteria) this;
        }

        public Criteria andStatusIdBetween(Integer value1, Integer value2) {
            addCriterion("status_id between", value1, value2, "statusId");
            return (Criteria) this;
        }

        public Criteria andStatusIdNotBetween(Integer value1, Integer value2) {
            addCriterion("status_id not between", value1, value2, "statusId");
            return (Criteria) this;
        }

        public Criteria andEmpNoteIsNull() {
            addCriterion("emp_note is null");
            return (Criteria) this;
        }

        public Criteria andEmpNoteIsNotNull() {
            addCriterion("emp_note is not null");
            return (Criteria) this;
        }

        public Criteria andEmpNoteEqualTo(String value) {
            addCriterion("emp_note =", value, "empNote");
            return (Criteria) this;
        }

        public Criteria andEmpNoteNotEqualTo(String value) {
            addCriterion("emp_note <>", value, "empNote");
            return (Criteria) this;
        }

        public Criteria andEmpNoteGreaterThan(String value) {
            addCriterion("emp_note >", value, "empNote");
            return (Criteria) this;
        }

        public Criteria andEmpNoteGreaterThanOrEqualTo(String value) {
            addCriterion("emp_note >=", value, "empNote");
            return (Criteria) this;
        }

        public Criteria andEmpNoteLessThan(String value) {
            addCriterion("emp_note <", value, "empNote");
            return (Criteria) this;
        }

        public Criteria andEmpNoteLessThanOrEqualTo(String value) {
            addCriterion("emp_note <=", value, "empNote");
            return (Criteria) this;
        }

        public Criteria andEmpNoteLike(String value) {
            addCriterion("emp_note like", value, "empNote");
            return (Criteria) this;
        }

        public Criteria andEmpNoteNotLike(String value) {
            addCriterion("emp_note not like", value, "empNote");
            return (Criteria) this;
        }

        public Criteria andEmpNoteIn(List<String> values) {
            addCriterion("emp_note in", values, "empNote");
            return (Criteria) this;
        }

        public Criteria andEmpNoteNotIn(List<String> values) {
            addCriterion("emp_note not in", values, "empNote");
            return (Criteria) this;
        }

        public Criteria andEmpNoteBetween(String value1, String value2) {
            addCriterion("emp_note between", value1, value2, "empNote");
            return (Criteria) this;
        }

        public Criteria andEmpNoteNotBetween(String value1, String value2) {
            addCriterion("emp_note not between", value1, value2, "empNote");
            return (Criteria) this;
        }

        public Criteria andLastOperatorDateIsNull() {
            addCriterion("last_operator_date is null");
            return (Criteria) this;
        }

        public Criteria andLastOperatorDateIsNotNull() {
            addCriterion("last_operator_date is not null");
            return (Criteria) this;
        }

        public Criteria andLastOperatorDateEqualTo(Date value) {
            addCriterion("last_operator_date =", value, "lastOperatorDate");
            return (Criteria) this;
        }

        public Criteria andLastOperatorDateNotEqualTo(Date value) {
            addCriterion("last_operator_date <>", value, "lastOperatorDate");
            return (Criteria) this;
        }

        public Criteria andLastOperatorDateGreaterThan(Date value) {
            addCriterion("last_operator_date >", value, "lastOperatorDate");
            return (Criteria) this;
        }

        public Criteria andLastOperatorDateGreaterThanOrEqualTo(Date value) {
            addCriterion("last_operator_date >=", value, "lastOperatorDate");
            return (Criteria) this;
        }

        public Criteria andLastOperatorDateLessThan(Date value) {
            addCriterion("last_operator_date <", value, "lastOperatorDate");
            return (Criteria) this;
        }

        public Criteria andLastOperatorDateLessThanOrEqualTo(Date value) {
            addCriterion("last_operator_date <=", value, "lastOperatorDate");
            return (Criteria) this;
        }

        public Criteria andLastOperatorDateIn(List<Date> values) {
            addCriterion("last_operator_date in", values, "lastOperatorDate");
            return (Criteria) this;
        }

        public Criteria andLastOperatorDateNotIn(List<Date> values) {
            addCriterion("last_operator_date not in", values, "lastOperatorDate");
            return (Criteria) this;
        }

        public Criteria andLastOperatorDateBetween(Date value1, Date value2) {
            addCriterion("last_operator_date between", value1, value2, "lastOperatorDate");
            return (Criteria) this;
        }

        public Criteria andLastOperatorDateNotBetween(Date value1, Date value2) {
            addCriterion("last_operator_date not between", value1, value2, "lastOperatorDate");
            return (Criteria) this;
        }

        public Criteria andOperatorEmpjobidIsNull() {
            addCriterion("operator_empJobId is null");
            return (Criteria) this;
        }

        public Criteria andOperatorEmpjobidIsNotNull() {
            addCriterion("operator_empJobId is not null");
            return (Criteria) this;
        }

        public Criteria andOperatorEmpjobidEqualTo(String value) {
            addCriterion("operator_empJobId =", value, "operatorEmpjobid");
            return (Criteria) this;
        }

        public Criteria andOperatorEmpjobidNotEqualTo(String value) {
            addCriterion("operator_empJobId <>", value, "operatorEmpjobid");
            return (Criteria) this;
        }

        public Criteria andOperatorEmpjobidGreaterThan(String value) {
            addCriterion("operator_empJobId >", value, "operatorEmpjobid");
            return (Criteria) this;
        }

        public Criteria andOperatorEmpjobidGreaterThanOrEqualTo(String value) {
            addCriterion("operator_empJobId >=", value, "operatorEmpjobid");
            return (Criteria) this;
        }

        public Criteria andOperatorEmpjobidLessThan(String value) {
            addCriterion("operator_empJobId <", value, "operatorEmpjobid");
            return (Criteria) this;
        }

        public Criteria andOperatorEmpjobidLessThanOrEqualTo(String value) {
            addCriterion("operator_empJobId <=", value, "operatorEmpjobid");
            return (Criteria) this;
        }

        public Criteria andOperatorEmpjobidLike(String value) {
            addCriterion("operator_empJobId like", value, "operatorEmpjobid");
            return (Criteria) this;
        }

        public Criteria andOperatorEmpjobidNotLike(String value) {
            addCriterion("operator_empJobId not like", value, "operatorEmpjobid");
            return (Criteria) this;
        }

        public Criteria andOperatorEmpjobidIn(List<String> values) {
            addCriterion("operator_empJobId in", values, "operatorEmpjobid");
            return (Criteria) this;
        }

        public Criteria andOperatorEmpjobidNotIn(List<String> values) {
            addCriterion("operator_empJobId not in", values, "operatorEmpjobid");
            return (Criteria) this;
        }

        public Criteria andOperatorEmpjobidBetween(String value1, String value2) {
            addCriterion("operator_empJobId between", value1, value2, "operatorEmpjobid");
            return (Criteria) this;
        }

        public Criteria andOperatorEmpjobidNotBetween(String value1, String value2) {
            addCriterion("operator_empJobId not between", value1, value2, "operatorEmpjobid");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table employee
     *
     * @mbg.generated do_not_delete_during_merge Sat Apr 04 14:05:24 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table employee
     *
     * @mbg.generated Sat Apr 04 14:05:24 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}