package com.lqs.hrm.entity;

/**
 * 职工-部门实体类
 * @author luckyliuqs
 *
 */
public class EmployeeDepartment {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_department.ed_id
     *
     * @mbg.generated Sun Apr 05 19:35:09 CST 2020
     */
    private Integer edId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_department.emp_jobId
     *
     * @mbg.generated Sun Apr 05 19:35:09 CST 2020
     */
    private String empJobid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_department.dept_id
     *
     * @mbg.generated Sun Apr 05 19:35:09 CST 2020
     */
    private Integer deptId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_department.ed_id
     *
     * @return the value of employee_department.ed_id
     *
     * @mbg.generated Sun Apr 05 19:35:09 CST 2020
     */
    public Integer getEdId() {
        return edId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_department.ed_id
     *
     * @param edId the value for employee_department.ed_id
     *
     * @mbg.generated Sun Apr 05 19:35:09 CST 2020
     */
    public void setEdId(Integer edId) {
        this.edId = edId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_department.emp_jobId
     *
     * @return the value of employee_department.emp_jobId
     *
     * @mbg.generated Sun Apr 05 19:35:09 CST 2020
     */
    public String getEmpJobid() {
        return empJobid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_department.emp_jobId
     *
     * @param empJobid the value for employee_department.emp_jobId
     *
     * @mbg.generated Sun Apr 05 19:35:09 CST 2020
     */
    public void setEmpJobid(String empJobid) {
        this.empJobid = empJobid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_department.dept_id
     *
     * @return the value of employee_department.dept_id
     *
     * @mbg.generated Sun Apr 05 19:35:09 CST 2020
     */
    public Integer getDeptId() {
        return deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_department.dept_id
     *
     * @param deptId the value for employee_department.dept_id
     *
     * @mbg.generated Sun Apr 05 19:35:09 CST 2020
     */
    public void setDeptId(Integer deptId) {
        this.deptId = deptId;
    }
}