package com.lqs.hrm.entity;

import java.util.Date;

/**
 * 职工离职实体类
 * @author luckyliuqs
 *
 */
public class EmployeeResign {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_resign.resign_id
     *
     * @mbg.generated Sat May 23 23:25:41 CST 2020
     */
    private Integer resignId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_resign.emp_jobId
     *
     * @mbg.generated Sat May 23 23:25:41 CST 2020
     */
    private String empJobid;
    
    /**
     * 离职的职工姓名
     */
    private String empName;

	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_resign.resign_date
     *
     * @mbg.generated Sat May 23 23:25:41 CST 2020
     */
    private Date resignDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_resign.resign_reason
     *
     * @mbg.generated Sat May 23 23:25:41 CST 2020
     */
    private String resignReason;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_resign.dept_id
     *
     * @mbg.generated Sat May 23 23:25:41 CST 2020
     */
    private Integer deptId;
    
    /**
     * 离职的部门名称
     */
    private String deptName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_resign.position_id
     *
     * @mbg.generated Sat May 23 23:25:41 CST 2020
     */
    private Integer positionId;
    
    /**
     * 离职的职位名称
     */
    private String positionName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_resign.apply_date
     *
     * @mbg.generated Sat May 23 23:25:41 CST 2020
     */
    private Date applyDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_resign.note
     *
     * @mbg.generated Sat May 23 23:25:41 CST 2020
     */
    private String note;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_resign.status_id
     *
     * @mbg.generated Sat May 23 23:25:41 CST 2020
     */
    private Integer statusId;
    
    /**
     * 状态名称
     */
    private String statusName = "";

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_resign.check_date
     *
     * @mbg.generated Sat May 23 23:25:41 CST 2020
     */
    private Date checkDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_resign.check_empJobId
     *
     * @mbg.generated Sat May 23 23:25:41 CST 2020
     */
    private String checkEmpjobid;
    
    /**
     * 审批人名称
     */
    private String checkEmpName = "";

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_resign.resign_id
     *
     * @return the value of employee_resign.resign_id
     *
     * @mbg.generated Sat May 23 23:25:41 CST 2020
     */
    public Integer getResignId() {
        return resignId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_resign.resign_id
     *
     * @param resignId the value for employee_resign.resign_id
     *
     * @mbg.generated Sat May 23 23:25:41 CST 2020
     */
    public void setResignId(Integer resignId) {
        this.resignId = resignId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_resign.emp_jobId
     *
     * @return the value of employee_resign.emp_jobId
     *
     * @mbg.generated Sat May 23 23:25:41 CST 2020
     */
    public String getEmpJobid() {
        return empJobid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_resign.emp_jobId
     *
     * @param empJobid the value for employee_resign.emp_jobId
     *
     * @mbg.generated Sat May 23 23:25:41 CST 2020
     */
    public void setEmpJobid(String empJobid) {
        this.empJobid = empJobid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_resign.resign_date
     *
     * @return the value of employee_resign.resign_date
     *
     * @mbg.generated Sat May 23 23:25:41 CST 2020
     */
    public Date getResignDate() {
        return resignDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_resign.resign_date
     *
     * @param resignDate the value for employee_resign.resign_date
     *
     * @mbg.generated Sat May 23 23:25:41 CST 2020
     */
    public void setResignDate(Date resignDate) {
        this.resignDate = resignDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_resign.resign_reason
     *
     * @return the value of employee_resign.resign_reason
     *
     * @mbg.generated Sat May 23 23:25:41 CST 2020
     */
    public String getResignReason() {
        return resignReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_resign.resign_reason
     *
     * @param resignReason the value for employee_resign.resign_reason
     *
     * @mbg.generated Sat May 23 23:25:41 CST 2020
     */
    public void setResignReason(String resignReason) {
        this.resignReason = resignReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_resign.dept_id
     *
     * @return the value of employee_resign.dept_id
     *
     * @mbg.generated Sat May 23 23:25:41 CST 2020
     */
    public Integer getDeptId() {
        return deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_resign.dept_id
     *
     * @param deptId the value for employee_resign.dept_id
     *
     * @mbg.generated Sat May 23 23:25:41 CST 2020
     */
    public void setDeptId(Integer deptId) {
        this.deptId = deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_resign.position_id
     *
     * @return the value of employee_resign.position_id
     *
     * @mbg.generated Sat May 23 23:25:41 CST 2020
     */
    public Integer getPositionId() {
        return positionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_resign.position_id
     *
     * @param positionId the value for employee_resign.position_id
     *
     * @mbg.generated Sat May 23 23:25:41 CST 2020
     */
    public void setPositionId(Integer positionId) {
        this.positionId = positionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_resign.apply_date
     *
     * @return the value of employee_resign.apply_date
     *
     * @mbg.generated Sat May 23 23:25:41 CST 2020
     */
    public Date getApplyDate() {
        return applyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_resign.apply_date
     *
     * @param applyDate the value for employee_resign.apply_date
     *
     * @mbg.generated Sat May 23 23:25:41 CST 2020
     */
    public void setApplyDate(Date applyDate) {
        this.applyDate = applyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_resign.note
     *
     * @return the value of employee_resign.note
     *
     * @mbg.generated Sat May 23 23:25:41 CST 2020
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_resign.note
     *
     * @param note the value for employee_resign.note
     *
     * @mbg.generated Sat May 23 23:25:41 CST 2020
     */
    public void setNote(String note) {
        this.note = note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_resign.status_id
     *
     * @return the value of employee_resign.status_id
     *
     * @mbg.generated Sat May 23 23:25:41 CST 2020
     */
    public Integer getStatusId() {
        return statusId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_resign.status_id
     *
     * @param statusId the value for employee_resign.status_id
     *
     * @mbg.generated Sat May 23 23:25:41 CST 2020
     */
    public void setStatusId(Integer statusId) {
        this.statusId = statusId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_resign.check_date
     *
     * @return the value of employee_resign.check_date
     *
     * @mbg.generated Sat May 23 23:25:41 CST 2020
     */
    public Date getCheckDate() {
        return checkDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_resign.check_date
     *
     * @param checkDate the value for employee_resign.check_date
     *
     * @mbg.generated Sat May 23 23:25:41 CST 2020
     */
    public void setCheckDate(Date checkDate) {
        this.checkDate = checkDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_resign.check_empJobId
     *
     * @return the value of employee_resign.check_empJobId
     *
     * @mbg.generated Sat May 23 23:25:41 CST 2020
     */
    public String getCheckEmpjobid() {
        return checkEmpjobid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_resign.check_empJobId
     *
     * @param checkEmpjobid the value for employee_resign.check_empJobId
     *
     * @mbg.generated Sat May 23 23:25:41 CST 2020
     */
    public void setCheckEmpjobid(String checkEmpjobid) {
        this.checkEmpjobid = checkEmpjobid;
    }

	public String getStatusName() {
		return statusName;
	}

	public void setStatusName(String statusName) {
		this.statusName = statusName;
	}

	public String getCheckEmpName() {
		return checkEmpName;
	}

	public void setCheckEmpName(String checkEmpName) {
		this.checkEmpName = checkEmpName;
	}

	public String getDeptName() {
		return deptName;
	}

	public void setDeptName(String deptName) {
		this.deptName = deptName;
	}

	public String getPositionName() {
		return positionName;
	}

	public void setPositionName(String positionName) {
		this.positionName = positionName;
	}
	public String getEmpName() {
		return empName;
	}

	public void setEmpName(String empName) {
		this.empName = empName;
	}
    
}