package com.lqs.hrm.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class EmployeeResignExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table employee_resign
	 * @mbg.generated  Mon May 25 00:12:19 CST 2020
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table employee_resign
	 * @mbg.generated  Mon May 25 00:12:19 CST 2020
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table employee_resign
	 * @mbg.generated  Mon May 25 00:12:19 CST 2020
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employee_resign
	 * @mbg.generated  Mon May 25 00:12:19 CST 2020
	 */
	public EmployeeResignExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employee_resign
	 * @mbg.generated  Mon May 25 00:12:19 CST 2020
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employee_resign
	 * @mbg.generated  Mon May 25 00:12:19 CST 2020
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employee_resign
	 * @mbg.generated  Mon May 25 00:12:19 CST 2020
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employee_resign
	 * @mbg.generated  Mon May 25 00:12:19 CST 2020
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employee_resign
	 * @mbg.generated  Mon May 25 00:12:19 CST 2020
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employee_resign
	 * @mbg.generated  Mon May 25 00:12:19 CST 2020
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employee_resign
	 * @mbg.generated  Mon May 25 00:12:19 CST 2020
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employee_resign
	 * @mbg.generated  Mon May 25 00:12:19 CST 2020
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employee_resign
	 * @mbg.generated  Mon May 25 00:12:19 CST 2020
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table employee_resign
	 * @mbg.generated  Mon May 25 00:12:19 CST 2020
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table employee_resign
	 * @mbg.generated  Mon May 25 00:12:19 CST 2020
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andResignIdIsNull() {
			addCriterion("resign_id is null");
			return (Criteria) this;
		}

		public Criteria andResignIdIsNotNull() {
			addCriterion("resign_id is not null");
			return (Criteria) this;
		}

		public Criteria andResignIdEqualTo(Integer value) {
			addCriterion("resign_id =", value, "resignId");
			return (Criteria) this;
		}

		public Criteria andResignIdNotEqualTo(Integer value) {
			addCriterion("resign_id <>", value, "resignId");
			return (Criteria) this;
		}

		public Criteria andResignIdGreaterThan(Integer value) {
			addCriterion("resign_id >", value, "resignId");
			return (Criteria) this;
		}

		public Criteria andResignIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("resign_id >=", value, "resignId");
			return (Criteria) this;
		}

		public Criteria andResignIdLessThan(Integer value) {
			addCriterion("resign_id <", value, "resignId");
			return (Criteria) this;
		}

		public Criteria andResignIdLessThanOrEqualTo(Integer value) {
			addCriterion("resign_id <=", value, "resignId");
			return (Criteria) this;
		}

		public Criteria andResignIdIn(List<Integer> values) {
			addCriterion("resign_id in", values, "resignId");
			return (Criteria) this;
		}

		public Criteria andResignIdNotIn(List<Integer> values) {
			addCriterion("resign_id not in", values, "resignId");
			return (Criteria) this;
		}

		public Criteria andResignIdBetween(Integer value1, Integer value2) {
			addCriterion("resign_id between", value1, value2, "resignId");
			return (Criteria) this;
		}

		public Criteria andResignIdNotBetween(Integer value1, Integer value2) {
			addCriterion("resign_id not between", value1, value2, "resignId");
			return (Criteria) this;
		}

		public Criteria andEmpJobidIsNull() {
			addCriterion("emp_jobId is null");
			return (Criteria) this;
		}

		public Criteria andEmpJobidIsNotNull() {
			addCriterion("emp_jobId is not null");
			return (Criteria) this;
		}

		public Criteria andEmpJobidEqualTo(String value) {
			addCriterion("emp_jobId =", value, "empJobid");
			return (Criteria) this;
		}

		public Criteria andEmpJobidNotEqualTo(String value) {
			addCriterion("emp_jobId <>", value, "empJobid");
			return (Criteria) this;
		}

		public Criteria andEmpJobidGreaterThan(String value) {
			addCriterion("emp_jobId >", value, "empJobid");
			return (Criteria) this;
		}

		public Criteria andEmpJobidGreaterThanOrEqualTo(String value) {
			addCriterion("emp_jobId >=", value, "empJobid");
			return (Criteria) this;
		}

		public Criteria andEmpJobidLessThan(String value) {
			addCriterion("emp_jobId <", value, "empJobid");
			return (Criteria) this;
		}

		public Criteria andEmpJobidLessThanOrEqualTo(String value) {
			addCriterion("emp_jobId <=", value, "empJobid");
			return (Criteria) this;
		}

		public Criteria andEmpJobidLike(String value) {
			addCriterion("emp_jobId like", value, "empJobid");
			return (Criteria) this;
		}

		public Criteria andEmpJobidNotLike(String value) {
			addCriterion("emp_jobId not like", value, "empJobid");
			return (Criteria) this;
		}

		public Criteria andEmpJobidIn(List<String> values) {
			addCriterion("emp_jobId in", values, "empJobid");
			return (Criteria) this;
		}

		public Criteria andEmpJobidNotIn(List<String> values) {
			addCriterion("emp_jobId not in", values, "empJobid");
			return (Criteria) this;
		}

		public Criteria andEmpJobidBetween(String value1, String value2) {
			addCriterion("emp_jobId between", value1, value2, "empJobid");
			return (Criteria) this;
		}

		public Criteria andEmpJobidNotBetween(String value1, String value2) {
			addCriterion("emp_jobId not between", value1, value2, "empJobid");
			return (Criteria) this;
		}

		public Criteria andResignDateIsNull() {
			addCriterion("resign_date is null");
			return (Criteria) this;
		}

		public Criteria andResignDateIsNotNull() {
			addCriterion("resign_date is not null");
			return (Criteria) this;
		}

		public Criteria andResignDateEqualTo(Date value) {
			addCriterion("resign_date =", value, "resignDate");
			return (Criteria) this;
		}

		public Criteria andResignDateNotEqualTo(Date value) {
			addCriterion("resign_date <>", value, "resignDate");
			return (Criteria) this;
		}

		public Criteria andResignDateGreaterThan(Date value) {
			addCriterion("resign_date >", value, "resignDate");
			return (Criteria) this;
		}

		public Criteria andResignDateGreaterThanOrEqualTo(Date value) {
			addCriterion("resign_date >=", value, "resignDate");
			return (Criteria) this;
		}

		public Criteria andResignDateLessThan(Date value) {
			addCriterion("resign_date <", value, "resignDate");
			return (Criteria) this;
		}

		public Criteria andResignDateLessThanOrEqualTo(Date value) {
			addCriterion("resign_date <=", value, "resignDate");
			return (Criteria) this;
		}

		public Criteria andResignDateIn(List<Date> values) {
			addCriterion("resign_date in", values, "resignDate");
			return (Criteria) this;
		}

		public Criteria andResignDateNotIn(List<Date> values) {
			addCriterion("resign_date not in", values, "resignDate");
			return (Criteria) this;
		}

		public Criteria andResignDateBetween(Date value1, Date value2) {
			addCriterion("resign_date between", value1, value2, "resignDate");
			return (Criteria) this;
		}

		public Criteria andResignDateNotBetween(Date value1, Date value2) {
			addCriterion("resign_date not between", value1, value2, "resignDate");
			return (Criteria) this;
		}

		public Criteria andResignReasonIsNull() {
			addCriterion("resign_reason is null");
			return (Criteria) this;
		}

		public Criteria andResignReasonIsNotNull() {
			addCriterion("resign_reason is not null");
			return (Criteria) this;
		}

		public Criteria andResignReasonEqualTo(String value) {
			addCriterion("resign_reason =", value, "resignReason");
			return (Criteria) this;
		}

		public Criteria andResignReasonNotEqualTo(String value) {
			addCriterion("resign_reason <>", value, "resignReason");
			return (Criteria) this;
		}

		public Criteria andResignReasonGreaterThan(String value) {
			addCriterion("resign_reason >", value, "resignReason");
			return (Criteria) this;
		}

		public Criteria andResignReasonGreaterThanOrEqualTo(String value) {
			addCriterion("resign_reason >=", value, "resignReason");
			return (Criteria) this;
		}

		public Criteria andResignReasonLessThan(String value) {
			addCriterion("resign_reason <", value, "resignReason");
			return (Criteria) this;
		}

		public Criteria andResignReasonLessThanOrEqualTo(String value) {
			addCriterion("resign_reason <=", value, "resignReason");
			return (Criteria) this;
		}

		public Criteria andResignReasonLike(String value) {
			addCriterion("resign_reason like", value, "resignReason");
			return (Criteria) this;
		}

		public Criteria andResignReasonNotLike(String value) {
			addCriterion("resign_reason not like", value, "resignReason");
			return (Criteria) this;
		}

		public Criteria andResignReasonIn(List<String> values) {
			addCriterion("resign_reason in", values, "resignReason");
			return (Criteria) this;
		}

		public Criteria andResignReasonNotIn(List<String> values) {
			addCriterion("resign_reason not in", values, "resignReason");
			return (Criteria) this;
		}

		public Criteria andResignReasonBetween(String value1, String value2) {
			addCriterion("resign_reason between", value1, value2, "resignReason");
			return (Criteria) this;
		}

		public Criteria andResignReasonNotBetween(String value1, String value2) {
			addCriterion("resign_reason not between", value1, value2, "resignReason");
			return (Criteria) this;
		}

		public Criteria andDeptIdIsNull() {
			addCriterion("dept_id is null");
			return (Criteria) this;
		}

		public Criteria andDeptIdIsNotNull() {
			addCriterion("dept_id is not null");
			return (Criteria) this;
		}

		public Criteria andDeptIdEqualTo(Integer value) {
			addCriterion("dept_id =", value, "deptId");
			return (Criteria) this;
		}

		public Criteria andDeptIdNotEqualTo(Integer value) {
			addCriterion("dept_id <>", value, "deptId");
			return (Criteria) this;
		}

		public Criteria andDeptIdGreaterThan(Integer value) {
			addCriterion("dept_id >", value, "deptId");
			return (Criteria) this;
		}

		public Criteria andDeptIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("dept_id >=", value, "deptId");
			return (Criteria) this;
		}

		public Criteria andDeptIdLessThan(Integer value) {
			addCriterion("dept_id <", value, "deptId");
			return (Criteria) this;
		}

		public Criteria andDeptIdLessThanOrEqualTo(Integer value) {
			addCriterion("dept_id <=", value, "deptId");
			return (Criteria) this;
		}

		public Criteria andDeptIdIn(List<Integer> values) {
			addCriterion("dept_id in", values, "deptId");
			return (Criteria) this;
		}

		public Criteria andDeptIdNotIn(List<Integer> values) {
			addCriterion("dept_id not in", values, "deptId");
			return (Criteria) this;
		}

		public Criteria andDeptIdBetween(Integer value1, Integer value2) {
			addCriterion("dept_id between", value1, value2, "deptId");
			return (Criteria) this;
		}

		public Criteria andDeptIdNotBetween(Integer value1, Integer value2) {
			addCriterion("dept_id not between", value1, value2, "deptId");
			return (Criteria) this;
		}

		public Criteria andPositionIdIsNull() {
			addCriterion("position_id is null");
			return (Criteria) this;
		}

		public Criteria andPositionIdIsNotNull() {
			addCriterion("position_id is not null");
			return (Criteria) this;
		}

		public Criteria andPositionIdEqualTo(Integer value) {
			addCriterion("position_id =", value, "positionId");
			return (Criteria) this;
		}

		public Criteria andPositionIdNotEqualTo(Integer value) {
			addCriterion("position_id <>", value, "positionId");
			return (Criteria) this;
		}

		public Criteria andPositionIdGreaterThan(Integer value) {
			addCriterion("position_id >", value, "positionId");
			return (Criteria) this;
		}

		public Criteria andPositionIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("position_id >=", value, "positionId");
			return (Criteria) this;
		}

		public Criteria andPositionIdLessThan(Integer value) {
			addCriterion("position_id <", value, "positionId");
			return (Criteria) this;
		}

		public Criteria andPositionIdLessThanOrEqualTo(Integer value) {
			addCriterion("position_id <=", value, "positionId");
			return (Criteria) this;
		}

		public Criteria andPositionIdIn(List<Integer> values) {
			addCriterion("position_id in", values, "positionId");
			return (Criteria) this;
		}

		public Criteria andPositionIdNotIn(List<Integer> values) {
			addCriterion("position_id not in", values, "positionId");
			return (Criteria) this;
		}

		public Criteria andPositionIdBetween(Integer value1, Integer value2) {
			addCriterion("position_id between", value1, value2, "positionId");
			return (Criteria) this;
		}

		public Criteria andPositionIdNotBetween(Integer value1, Integer value2) {
			addCriterion("position_id not between", value1, value2, "positionId");
			return (Criteria) this;
		}

		public Criteria andApplyDateIsNull() {
			addCriterion("apply_date is null");
			return (Criteria) this;
		}

		public Criteria andApplyDateIsNotNull() {
			addCriterion("apply_date is not null");
			return (Criteria) this;
		}

		public Criteria andApplyDateEqualTo(Date value) {
			addCriterion("apply_date =", value, "applyDate");
			return (Criteria) this;
		}

		public Criteria andApplyDateNotEqualTo(Date value) {
			addCriterion("apply_date <>", value, "applyDate");
			return (Criteria) this;
		}

		public Criteria andApplyDateGreaterThan(Date value) {
			addCriterion("apply_date >", value, "applyDate");
			return (Criteria) this;
		}

		public Criteria andApplyDateGreaterThanOrEqualTo(Date value) {
			addCriterion("apply_date >=", value, "applyDate");
			return (Criteria) this;
		}

		public Criteria andApplyDateLessThan(Date value) {
			addCriterion("apply_date <", value, "applyDate");
			return (Criteria) this;
		}

		public Criteria andApplyDateLessThanOrEqualTo(Date value) {
			addCriterion("apply_date <=", value, "applyDate");
			return (Criteria) this;
		}

		public Criteria andApplyDateIn(List<Date> values) {
			addCriterion("apply_date in", values, "applyDate");
			return (Criteria) this;
		}

		public Criteria andApplyDateNotIn(List<Date> values) {
			addCriterion("apply_date not in", values, "applyDate");
			return (Criteria) this;
		}

		public Criteria andApplyDateBetween(Date value1, Date value2) {
			addCriterion("apply_date between", value1, value2, "applyDate");
			return (Criteria) this;
		}

		public Criteria andApplyDateNotBetween(Date value1, Date value2) {
			addCriterion("apply_date not between", value1, value2, "applyDate");
			return (Criteria) this;
		}

		public Criteria andNoteIsNull() {
			addCriterion("note is null");
			return (Criteria) this;
		}

		public Criteria andNoteIsNotNull() {
			addCriterion("note is not null");
			return (Criteria) this;
		}

		public Criteria andNoteEqualTo(String value) {
			addCriterion("note =", value, "note");
			return (Criteria) this;
		}

		public Criteria andNoteNotEqualTo(String value) {
			addCriterion("note <>", value, "note");
			return (Criteria) this;
		}

		public Criteria andNoteGreaterThan(String value) {
			addCriterion("note >", value, "note");
			return (Criteria) this;
		}

		public Criteria andNoteGreaterThanOrEqualTo(String value) {
			addCriterion("note >=", value, "note");
			return (Criteria) this;
		}

		public Criteria andNoteLessThan(String value) {
			addCriterion("note <", value, "note");
			return (Criteria) this;
		}

		public Criteria andNoteLessThanOrEqualTo(String value) {
			addCriterion("note <=", value, "note");
			return (Criteria) this;
		}

		public Criteria andNoteLike(String value) {
			addCriterion("note like", value, "note");
			return (Criteria) this;
		}

		public Criteria andNoteNotLike(String value) {
			addCriterion("note not like", value, "note");
			return (Criteria) this;
		}

		public Criteria andNoteIn(List<String> values) {
			addCriterion("note in", values, "note");
			return (Criteria) this;
		}

		public Criteria andNoteNotIn(List<String> values) {
			addCriterion("note not in", values, "note");
			return (Criteria) this;
		}

		public Criteria andNoteBetween(String value1, String value2) {
			addCriterion("note between", value1, value2, "note");
			return (Criteria) this;
		}

		public Criteria andNoteNotBetween(String value1, String value2) {
			addCriterion("note not between", value1, value2, "note");
			return (Criteria) this;
		}

		public Criteria andStatusIdIsNull() {
			addCriterion("status_id is null");
			return (Criteria) this;
		}

		public Criteria andStatusIdIsNotNull() {
			addCriterion("status_id is not null");
			return (Criteria) this;
		}

		public Criteria andStatusIdEqualTo(Integer value) {
			addCriterion("status_id =", value, "statusId");
			return (Criteria) this;
		}

		public Criteria andStatusIdNotEqualTo(Integer value) {
			addCriterion("status_id <>", value, "statusId");
			return (Criteria) this;
		}

		public Criteria andStatusIdGreaterThan(Integer value) {
			addCriterion("status_id >", value, "statusId");
			return (Criteria) this;
		}

		public Criteria andStatusIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("status_id >=", value, "statusId");
			return (Criteria) this;
		}

		public Criteria andStatusIdLessThan(Integer value) {
			addCriterion("status_id <", value, "statusId");
			return (Criteria) this;
		}

		public Criteria andStatusIdLessThanOrEqualTo(Integer value) {
			addCriterion("status_id <=", value, "statusId");
			return (Criteria) this;
		}

		public Criteria andStatusIdIn(List<Integer> values) {
			addCriterion("status_id in", values, "statusId");
			return (Criteria) this;
		}

		public Criteria andStatusIdNotIn(List<Integer> values) {
			addCriterion("status_id not in", values, "statusId");
			return (Criteria) this;
		}

		public Criteria andStatusIdBetween(Integer value1, Integer value2) {
			addCriterion("status_id between", value1, value2, "statusId");
			return (Criteria) this;
		}

		public Criteria andStatusIdNotBetween(Integer value1, Integer value2) {
			addCriterion("status_id not between", value1, value2, "statusId");
			return (Criteria) this;
		}

		public Criteria andCheckDateIsNull() {
			addCriterion("check_date is null");
			return (Criteria) this;
		}

		public Criteria andCheckDateIsNotNull() {
			addCriterion("check_date is not null");
			return (Criteria) this;
		}

		public Criteria andCheckDateEqualTo(Date value) {
			addCriterion("check_date =", value, "checkDate");
			return (Criteria) this;
		}

		public Criteria andCheckDateNotEqualTo(Date value) {
			addCriterion("check_date <>", value, "checkDate");
			return (Criteria) this;
		}

		public Criteria andCheckDateGreaterThan(Date value) {
			addCriterion("check_date >", value, "checkDate");
			return (Criteria) this;
		}

		public Criteria andCheckDateGreaterThanOrEqualTo(Date value) {
			addCriterion("check_date >=", value, "checkDate");
			return (Criteria) this;
		}

		public Criteria andCheckDateLessThan(Date value) {
			addCriterion("check_date <", value, "checkDate");
			return (Criteria) this;
		}

		public Criteria andCheckDateLessThanOrEqualTo(Date value) {
			addCriterion("check_date <=", value, "checkDate");
			return (Criteria) this;
		}

		public Criteria andCheckDateIn(List<Date> values) {
			addCriterion("check_date in", values, "checkDate");
			return (Criteria) this;
		}

		public Criteria andCheckDateNotIn(List<Date> values) {
			addCriterion("check_date not in", values, "checkDate");
			return (Criteria) this;
		}

		public Criteria andCheckDateBetween(Date value1, Date value2) {
			addCriterion("check_date between", value1, value2, "checkDate");
			return (Criteria) this;
		}

		public Criteria andCheckDateNotBetween(Date value1, Date value2) {
			addCriterion("check_date not between", value1, value2, "checkDate");
			return (Criteria) this;
		}

		public Criteria andCheckEmpjobidIsNull() {
			addCriterion("check_empJobId is null");
			return (Criteria) this;
		}

		public Criteria andCheckEmpjobidIsNotNull() {
			addCriterion("check_empJobId is not null");
			return (Criteria) this;
		}

		public Criteria andCheckEmpjobidEqualTo(String value) {
			addCriterion("check_empJobId =", value, "checkEmpjobid");
			return (Criteria) this;
		}

		public Criteria andCheckEmpjobidNotEqualTo(String value) {
			addCriterion("check_empJobId <>", value, "checkEmpjobid");
			return (Criteria) this;
		}

		public Criteria andCheckEmpjobidGreaterThan(String value) {
			addCriterion("check_empJobId >", value, "checkEmpjobid");
			return (Criteria) this;
		}

		public Criteria andCheckEmpjobidGreaterThanOrEqualTo(String value) {
			addCriterion("check_empJobId >=", value, "checkEmpjobid");
			return (Criteria) this;
		}

		public Criteria andCheckEmpjobidLessThan(String value) {
			addCriterion("check_empJobId <", value, "checkEmpjobid");
			return (Criteria) this;
		}

		public Criteria andCheckEmpjobidLessThanOrEqualTo(String value) {
			addCriterion("check_empJobId <=", value, "checkEmpjobid");
			return (Criteria) this;
		}

		public Criteria andCheckEmpjobidLike(String value) {
			addCriterion("check_empJobId like", value, "checkEmpjobid");
			return (Criteria) this;
		}

		public Criteria andCheckEmpjobidNotLike(String value) {
			addCriterion("check_empJobId not like", value, "checkEmpjobid");
			return (Criteria) this;
		}

		public Criteria andCheckEmpjobidIn(List<String> values) {
			addCriterion("check_empJobId in", values, "checkEmpjobid");
			return (Criteria) this;
		}

		public Criteria andCheckEmpjobidNotIn(List<String> values) {
			addCriterion("check_empJobId not in", values, "checkEmpjobid");
			return (Criteria) this;
		}

		public Criteria andCheckEmpjobidBetween(String value1, String value2) {
			addCriterion("check_empJobId between", value1, value2, "checkEmpjobid");
			return (Criteria) this;
		}

		public Criteria andCheckEmpjobidNotBetween(String value1, String value2) {
			addCriterion("check_empJobId not between", value1, value2, "checkEmpjobid");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table employee_resign
	 * @mbg.generated  Mon May 25 00:12:19 CST 2020
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table employee_resign
     *
     * @mbg.generated do_not_delete_during_merge Sat May 23 23:25:41 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}