package com.lqs.hrm.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class PositionExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table position
	 * @mbg.generated  Mon May 25 00:11:54 CST 2020
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table position
	 * @mbg.generated  Mon May 25 00:11:54 CST 2020
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table position
	 * @mbg.generated  Mon May 25 00:11:54 CST 2020
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table position
	 * @mbg.generated  Mon May 25 00:11:54 CST 2020
	 */
	public PositionExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table position
	 * @mbg.generated  Mon May 25 00:11:54 CST 2020
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table position
	 * @mbg.generated  Mon May 25 00:11:54 CST 2020
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table position
	 * @mbg.generated  Mon May 25 00:11:54 CST 2020
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table position
	 * @mbg.generated  Mon May 25 00:11:54 CST 2020
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table position
	 * @mbg.generated  Mon May 25 00:11:54 CST 2020
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table position
	 * @mbg.generated  Mon May 25 00:11:54 CST 2020
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table position
	 * @mbg.generated  Mon May 25 00:11:54 CST 2020
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table position
	 * @mbg.generated  Mon May 25 00:11:54 CST 2020
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table position
	 * @mbg.generated  Mon May 25 00:11:54 CST 2020
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table position
	 * @mbg.generated  Mon May 25 00:11:54 CST 2020
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table position
	 * @mbg.generated  Mon May 25 00:11:54 CST 2020
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andPositionIdIsNull() {
			addCriterion("position_id is null");
			return (Criteria) this;
		}

		public Criteria andPositionIdIsNotNull() {
			addCriterion("position_id is not null");
			return (Criteria) this;
		}

		public Criteria andPositionIdEqualTo(Integer value) {
			addCriterion("position_id =", value, "positionId");
			return (Criteria) this;
		}

		public Criteria andPositionIdNotEqualTo(Integer value) {
			addCriterion("position_id <>", value, "positionId");
			return (Criteria) this;
		}

		public Criteria andPositionIdGreaterThan(Integer value) {
			addCriterion("position_id >", value, "positionId");
			return (Criteria) this;
		}

		public Criteria andPositionIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("position_id >=", value, "positionId");
			return (Criteria) this;
		}

		public Criteria andPositionIdLessThan(Integer value) {
			addCriterion("position_id <", value, "positionId");
			return (Criteria) this;
		}

		public Criteria andPositionIdLessThanOrEqualTo(Integer value) {
			addCriterion("position_id <=", value, "positionId");
			return (Criteria) this;
		}

		public Criteria andPositionIdIn(List<Integer> values) {
			addCriterion("position_id in", values, "positionId");
			return (Criteria) this;
		}

		public Criteria andPositionIdNotIn(List<Integer> values) {
			addCriterion("position_id not in", values, "positionId");
			return (Criteria) this;
		}

		public Criteria andPositionIdBetween(Integer value1, Integer value2) {
			addCriterion("position_id between", value1, value2, "positionId");
			return (Criteria) this;
		}

		public Criteria andPositionIdNotBetween(Integer value1, Integer value2) {
			addCriterion("position_id not between", value1, value2, "positionId");
			return (Criteria) this;
		}

		public Criteria andPositionNameIsNull() {
			addCriterion("position_name is null");
			return (Criteria) this;
		}

		public Criteria andPositionNameIsNotNull() {
			addCriterion("position_name is not null");
			return (Criteria) this;
		}

		public Criteria andPositionNameEqualTo(String value) {
			addCriterion("position_name =", value, "positionName");
			return (Criteria) this;
		}

		public Criteria andPositionNameNotEqualTo(String value) {
			addCriterion("position_name <>", value, "positionName");
			return (Criteria) this;
		}

		public Criteria andPositionNameGreaterThan(String value) {
			addCriterion("position_name >", value, "positionName");
			return (Criteria) this;
		}

		public Criteria andPositionNameGreaterThanOrEqualTo(String value) {
			addCriterion("position_name >=", value, "positionName");
			return (Criteria) this;
		}

		public Criteria andPositionNameLessThan(String value) {
			addCriterion("position_name <", value, "positionName");
			return (Criteria) this;
		}

		public Criteria andPositionNameLessThanOrEqualTo(String value) {
			addCriterion("position_name <=", value, "positionName");
			return (Criteria) this;
		}

		public Criteria andPositionNameLike(String value) {
			addCriterion("position_name like", value, "positionName");
			return (Criteria) this;
		}

		public Criteria andPositionNameNotLike(String value) {
			addCriterion("position_name not like", value, "positionName");
			return (Criteria) this;
		}

		public Criteria andPositionNameIn(List<String> values) {
			addCriterion("position_name in", values, "positionName");
			return (Criteria) this;
		}

		public Criteria andPositionNameNotIn(List<String> values) {
			addCriterion("position_name not in", values, "positionName");
			return (Criteria) this;
		}

		public Criteria andPositionNameBetween(String value1, String value2) {
			addCriterion("position_name between", value1, value2, "positionName");
			return (Criteria) this;
		}

		public Criteria andPositionNameNotBetween(String value1, String value2) {
			addCriterion("position_name not between", value1, value2, "positionName");
			return (Criteria) this;
		}

		public Criteria andPositionDescIsNull() {
			addCriterion("position_desc is null");
			return (Criteria) this;
		}

		public Criteria andPositionDescIsNotNull() {
			addCriterion("position_desc is not null");
			return (Criteria) this;
		}

		public Criteria andPositionDescEqualTo(String value) {
			addCriterion("position_desc =", value, "positionDesc");
			return (Criteria) this;
		}

		public Criteria andPositionDescNotEqualTo(String value) {
			addCriterion("position_desc <>", value, "positionDesc");
			return (Criteria) this;
		}

		public Criteria andPositionDescGreaterThan(String value) {
			addCriterion("position_desc >", value, "positionDesc");
			return (Criteria) this;
		}

		public Criteria andPositionDescGreaterThanOrEqualTo(String value) {
			addCriterion("position_desc >=", value, "positionDesc");
			return (Criteria) this;
		}

		public Criteria andPositionDescLessThan(String value) {
			addCriterion("position_desc <", value, "positionDesc");
			return (Criteria) this;
		}

		public Criteria andPositionDescLessThanOrEqualTo(String value) {
			addCriterion("position_desc <=", value, "positionDesc");
			return (Criteria) this;
		}

		public Criteria andPositionDescLike(String value) {
			addCriterion("position_desc like", value, "positionDesc");
			return (Criteria) this;
		}

		public Criteria andPositionDescNotLike(String value) {
			addCriterion("position_desc not like", value, "positionDesc");
			return (Criteria) this;
		}

		public Criteria andPositionDescIn(List<String> values) {
			addCriterion("position_desc in", values, "positionDesc");
			return (Criteria) this;
		}

		public Criteria andPositionDescNotIn(List<String> values) {
			addCriterion("position_desc not in", values, "positionDesc");
			return (Criteria) this;
		}

		public Criteria andPositionDescBetween(String value1, String value2) {
			addCriterion("position_desc between", value1, value2, "positionDesc");
			return (Criteria) this;
		}

		public Criteria andPositionDescNotBetween(String value1, String value2) {
			addCriterion("position_desc not between", value1, value2, "positionDesc");
			return (Criteria) this;
		}

		public Criteria andPlIdIsNull() {
			addCriterion("pl_id is null");
			return (Criteria) this;
		}

		public Criteria andPlIdIsNotNull() {
			addCriterion("pl_id is not null");
			return (Criteria) this;
		}

		public Criteria andPlIdEqualTo(Integer value) {
			addCriterion("pl_id =", value, "plId");
			return (Criteria) this;
		}

		public Criteria andPlIdNotEqualTo(Integer value) {
			addCriterion("pl_id <>", value, "plId");
			return (Criteria) this;
		}

		public Criteria andPlIdGreaterThan(Integer value) {
			addCriterion("pl_id >", value, "plId");
			return (Criteria) this;
		}

		public Criteria andPlIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("pl_id >=", value, "plId");
			return (Criteria) this;
		}

		public Criteria andPlIdLessThan(Integer value) {
			addCriterion("pl_id <", value, "plId");
			return (Criteria) this;
		}

		public Criteria andPlIdLessThanOrEqualTo(Integer value) {
			addCriterion("pl_id <=", value, "plId");
			return (Criteria) this;
		}

		public Criteria andPlIdIn(List<Integer> values) {
			addCriterion("pl_id in", values, "plId");
			return (Criteria) this;
		}

		public Criteria andPlIdNotIn(List<Integer> values) {
			addCriterion("pl_id not in", values, "plId");
			return (Criteria) this;
		}

		public Criteria andPlIdBetween(Integer value1, Integer value2) {
			addCriterion("pl_id between", value1, value2, "plId");
			return (Criteria) this;
		}

		public Criteria andPlIdNotBetween(Integer value1, Integer value2) {
			addCriterion("pl_id not between", value1, value2, "plId");
			return (Criteria) this;
		}

		public Criteria andDeptIdIsNull() {
			addCriterion("dept_id is null");
			return (Criteria) this;
		}

		public Criteria andDeptIdIsNotNull() {
			addCriterion("dept_id is not null");
			return (Criteria) this;
		}

		public Criteria andDeptIdEqualTo(Integer value) {
			addCriterion("dept_id =", value, "deptId");
			return (Criteria) this;
		}

		public Criteria andDeptIdNotEqualTo(Integer value) {
			addCriterion("dept_id <>", value, "deptId");
			return (Criteria) this;
		}

		public Criteria andDeptIdGreaterThan(Integer value) {
			addCriterion("dept_id >", value, "deptId");
			return (Criteria) this;
		}

		public Criteria andDeptIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("dept_id >=", value, "deptId");
			return (Criteria) this;
		}

		public Criteria andDeptIdLessThan(Integer value) {
			addCriterion("dept_id <", value, "deptId");
			return (Criteria) this;
		}

		public Criteria andDeptIdLessThanOrEqualTo(Integer value) {
			addCriterion("dept_id <=", value, "deptId");
			return (Criteria) this;
		}

		public Criteria andDeptIdIn(List<Integer> values) {
			addCriterion("dept_id in", values, "deptId");
			return (Criteria) this;
		}

		public Criteria andDeptIdNotIn(List<Integer> values) {
			addCriterion("dept_id not in", values, "deptId");
			return (Criteria) this;
		}

		public Criteria andDeptIdBetween(Integer value1, Integer value2) {
			addCriterion("dept_id between", value1, value2, "deptId");
			return (Criteria) this;
		}

		public Criteria andDeptIdNotBetween(Integer value1, Integer value2) {
			addCriterion("dept_id not between", value1, value2, "deptId");
			return (Criteria) this;
		}

		public Criteria andParentPositionidIsNull() {
			addCriterion("parent_positionId is null");
			return (Criteria) this;
		}

		public Criteria andParentPositionidIsNotNull() {
			addCriterion("parent_positionId is not null");
			return (Criteria) this;
		}

		public Criteria andParentPositionidEqualTo(Integer value) {
			addCriterion("parent_positionId =", value, "parentPositionid");
			return (Criteria) this;
		}

		public Criteria andParentPositionidNotEqualTo(Integer value) {
			addCriterion("parent_positionId <>", value, "parentPositionid");
			return (Criteria) this;
		}

		public Criteria andParentPositionidGreaterThan(Integer value) {
			addCriterion("parent_positionId >", value, "parentPositionid");
			return (Criteria) this;
		}

		public Criteria andParentPositionidGreaterThanOrEqualTo(Integer value) {
			addCriterion("parent_positionId >=", value, "parentPositionid");
			return (Criteria) this;
		}

		public Criteria andParentPositionidLessThan(Integer value) {
			addCriterion("parent_positionId <", value, "parentPositionid");
			return (Criteria) this;
		}

		public Criteria andParentPositionidLessThanOrEqualTo(Integer value) {
			addCriterion("parent_positionId <=", value, "parentPositionid");
			return (Criteria) this;
		}

		public Criteria andParentPositionidIn(List<Integer> values) {
			addCriterion("parent_positionId in", values, "parentPositionid");
			return (Criteria) this;
		}

		public Criteria andParentPositionidNotIn(List<Integer> values) {
			addCriterion("parent_positionId not in", values, "parentPositionid");
			return (Criteria) this;
		}

		public Criteria andParentPositionidBetween(Integer value1, Integer value2) {
			addCriterion("parent_positionId between", value1, value2, "parentPositionid");
			return (Criteria) this;
		}

		public Criteria andParentPositionidNotBetween(Integer value1, Integer value2) {
			addCriterion("parent_positionId not between", value1, value2, "parentPositionid");
			return (Criteria) this;
		}

		public Criteria andStatusIdIsNull() {
			addCriterion("status_id is null");
			return (Criteria) this;
		}

		public Criteria andStatusIdIsNotNull() {
			addCriterion("status_id is not null");
			return (Criteria) this;
		}

		public Criteria andStatusIdEqualTo(Integer value) {
			addCriterion("status_id =", value, "statusId");
			return (Criteria) this;
		}

		public Criteria andStatusIdNotEqualTo(Integer value) {
			addCriterion("status_id <>", value, "statusId");
			return (Criteria) this;
		}

		public Criteria andStatusIdGreaterThan(Integer value) {
			addCriterion("status_id >", value, "statusId");
			return (Criteria) this;
		}

		public Criteria andStatusIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("status_id >=", value, "statusId");
			return (Criteria) this;
		}

		public Criteria andStatusIdLessThan(Integer value) {
			addCriterion("status_id <", value, "statusId");
			return (Criteria) this;
		}

		public Criteria andStatusIdLessThanOrEqualTo(Integer value) {
			addCriterion("status_id <=", value, "statusId");
			return (Criteria) this;
		}

		public Criteria andStatusIdIn(List<Integer> values) {
			addCriterion("status_id in", values, "statusId");
			return (Criteria) this;
		}

		public Criteria andStatusIdNotIn(List<Integer> values) {
			addCriterion("status_id not in", values, "statusId");
			return (Criteria) this;
		}

		public Criteria andStatusIdBetween(Integer value1, Integer value2) {
			addCriterion("status_id between", value1, value2, "statusId");
			return (Criteria) this;
		}

		public Criteria andStatusIdNotBetween(Integer value1, Integer value2) {
			addCriterion("status_id not between", value1, value2, "statusId");
			return (Criteria) this;
		}

		public Criteria andLastOperatorDateIsNull() {
			addCriterion("last_operator_date is null");
			return (Criteria) this;
		}

		public Criteria andLastOperatorDateIsNotNull() {
			addCriterion("last_operator_date is not null");
			return (Criteria) this;
		}

		public Criteria andLastOperatorDateEqualTo(Date value) {
			addCriterion("last_operator_date =", value, "lastOperatorDate");
			return (Criteria) this;
		}

		public Criteria andLastOperatorDateNotEqualTo(Date value) {
			addCriterion("last_operator_date <>", value, "lastOperatorDate");
			return (Criteria) this;
		}

		public Criteria andLastOperatorDateGreaterThan(Date value) {
			addCriterion("last_operator_date >", value, "lastOperatorDate");
			return (Criteria) this;
		}

		public Criteria andLastOperatorDateGreaterThanOrEqualTo(Date value) {
			addCriterion("last_operator_date >=", value, "lastOperatorDate");
			return (Criteria) this;
		}

		public Criteria andLastOperatorDateLessThan(Date value) {
			addCriterion("last_operator_date <", value, "lastOperatorDate");
			return (Criteria) this;
		}

		public Criteria andLastOperatorDateLessThanOrEqualTo(Date value) {
			addCriterion("last_operator_date <=", value, "lastOperatorDate");
			return (Criteria) this;
		}

		public Criteria andLastOperatorDateIn(List<Date> values) {
			addCriterion("last_operator_date in", values, "lastOperatorDate");
			return (Criteria) this;
		}

		public Criteria andLastOperatorDateNotIn(List<Date> values) {
			addCriterion("last_operator_date not in", values, "lastOperatorDate");
			return (Criteria) this;
		}

		public Criteria andLastOperatorDateBetween(Date value1, Date value2) {
			addCriterion("last_operator_date between", value1, value2, "lastOperatorDate");
			return (Criteria) this;
		}

		public Criteria andLastOperatorDateNotBetween(Date value1, Date value2) {
			addCriterion("last_operator_date not between", value1, value2, "lastOperatorDate");
			return (Criteria) this;
		}

		public Criteria andOperatorEmpjobidIsNull() {
			addCriterion("operator_empJobId is null");
			return (Criteria) this;
		}

		public Criteria andOperatorEmpjobidIsNotNull() {
			addCriterion("operator_empJobId is not null");
			return (Criteria) this;
		}

		public Criteria andOperatorEmpjobidEqualTo(String value) {
			addCriterion("operator_empJobId =", value, "operatorEmpjobid");
			return (Criteria) this;
		}

		public Criteria andOperatorEmpjobidNotEqualTo(String value) {
			addCriterion("operator_empJobId <>", value, "operatorEmpjobid");
			return (Criteria) this;
		}

		public Criteria andOperatorEmpjobidGreaterThan(String value) {
			addCriterion("operator_empJobId >", value, "operatorEmpjobid");
			return (Criteria) this;
		}

		public Criteria andOperatorEmpjobidGreaterThanOrEqualTo(String value) {
			addCriterion("operator_empJobId >=", value, "operatorEmpjobid");
			return (Criteria) this;
		}

		public Criteria andOperatorEmpjobidLessThan(String value) {
			addCriterion("operator_empJobId <", value, "operatorEmpjobid");
			return (Criteria) this;
		}

		public Criteria andOperatorEmpjobidLessThanOrEqualTo(String value) {
			addCriterion("operator_empJobId <=", value, "operatorEmpjobid");
			return (Criteria) this;
		}

		public Criteria andOperatorEmpjobidLike(String value) {
			addCriterion("operator_empJobId like", value, "operatorEmpjobid");
			return (Criteria) this;
		}

		public Criteria andOperatorEmpjobidNotLike(String value) {
			addCriterion("operator_empJobId not like", value, "operatorEmpjobid");
			return (Criteria) this;
		}

		public Criteria andOperatorEmpjobidIn(List<String> values) {
			addCriterion("operator_empJobId in", values, "operatorEmpjobid");
			return (Criteria) this;
		}

		public Criteria andOperatorEmpjobidNotIn(List<String> values) {
			addCriterion("operator_empJobId not in", values, "operatorEmpjobid");
			return (Criteria) this;
		}

		public Criteria andOperatorEmpjobidBetween(String value1, String value2) {
			addCriterion("operator_empJobId between", value1, value2, "operatorEmpjobid");
			return (Criteria) this;
		}

		public Criteria andOperatorEmpjobidNotBetween(String value1, String value2) {
			addCriterion("operator_empJobId not between", value1, value2, "operatorEmpjobid");
			return (Criteria) this;
		}

		public Criteria andIsOnlyIsNull() {
			addCriterion("is_only is null");
			return (Criteria) this;
		}

		public Criteria andIsOnlyIsNotNull() {
			addCriterion("is_only is not null");
			return (Criteria) this;
		}

		public Criteria andIsOnlyEqualTo(Boolean value) {
			addCriterion("is_only =", value, "isOnly");
			return (Criteria) this;
		}

		public Criteria andIsOnlyNotEqualTo(Boolean value) {
			addCriterion("is_only <>", value, "isOnly");
			return (Criteria) this;
		}

		public Criteria andIsOnlyGreaterThan(Boolean value) {
			addCriterion("is_only >", value, "isOnly");
			return (Criteria) this;
		}

		public Criteria andIsOnlyGreaterThanOrEqualTo(Boolean value) {
			addCriterion("is_only >=", value, "isOnly");
			return (Criteria) this;
		}

		public Criteria andIsOnlyLessThan(Boolean value) {
			addCriterion("is_only <", value, "isOnly");
			return (Criteria) this;
		}

		public Criteria andIsOnlyLessThanOrEqualTo(Boolean value) {
			addCriterion("is_only <=", value, "isOnly");
			return (Criteria) this;
		}

		public Criteria andIsOnlyIn(List<Boolean> values) {
			addCriterion("is_only in", values, "isOnly");
			return (Criteria) this;
		}

		public Criteria andIsOnlyNotIn(List<Boolean> values) {
			addCriterion("is_only not in", values, "isOnly");
			return (Criteria) this;
		}

		public Criteria andIsOnlyBetween(Boolean value1, Boolean value2) {
			addCriterion("is_only between", value1, value2, "isOnly");
			return (Criteria) this;
		}

		public Criteria andIsOnlyNotBetween(Boolean value1, Boolean value2) {
			addCriterion("is_only not between", value1, value2, "isOnly");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table position
	 * @mbg.generated  Mon May 25 00:11:54 CST 2020
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table position
     *
     * @mbg.generated do_not_delete_during_merge Thu May 21 00:37:07 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}