package com.lqs.hrm.entity;

import java.util.Date;

/**
 * 角色实体类
 * @author luckyliuqs
 *
 */
public class Roles {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column roles.role_id
	 * @mbg.generated  Thu May 28 23:47:37 CST 2020
	 */
	private Integer roleId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column roles.role_name
	 * @mbg.generated  Thu May 28 23:47:37 CST 2020
	 */
	private String roleName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column roles.role_desc
	 * @mbg.generated  Thu May 28 23:47:37 CST 2020
	 */
	private String roleDesc;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column roles.last_operatordate
	 * @mbg.generated  Thu May 28 23:47:37 CST 2020
	 */
	private Date lastOperatordate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column roles.operator_empJobId
	 * @mbg.generated  Thu May 28 23:47:37 CST 2020
	 */
	private String operatorEmpjobid;
	
	/**
	 * 最后一次操作人姓名
	 */
	private String operatorEmpName;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column roles.role_id
	 * @return  the value of roles.role_id
	 * @mbg.generated  Thu May 28 23:47:37 CST 2020
	 */
	public Integer getRoleId() {
		return roleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column roles.role_id
	 * @param roleId  the value for roles.role_id
	 * @mbg.generated  Thu May 28 23:47:37 CST 2020
	 */
	public void setRoleId(Integer roleId) {
		this.roleId = roleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column roles.role_name
	 * @return  the value of roles.role_name
	 * @mbg.generated  Thu May 28 23:47:37 CST 2020
	 */
	public String getRoleName() {
		return roleName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column roles.role_name
	 * @param roleName  the value for roles.role_name
	 * @mbg.generated  Thu May 28 23:47:37 CST 2020
	 */
	public void setRoleName(String roleName) {
		this.roleName = roleName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column roles.role_desc
	 * @return  the value of roles.role_desc
	 * @mbg.generated  Thu May 28 23:47:37 CST 2020
	 */
	public String getRoleDesc() {
		return roleDesc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column roles.role_desc
	 * @param roleDesc  the value for roles.role_desc
	 * @mbg.generated  Thu May 28 23:47:37 CST 2020
	 */
	public void setRoleDesc(String roleDesc) {
		this.roleDesc = roleDesc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column roles.last_operatordate
	 * @return  the value of roles.last_operatordate
	 * @mbg.generated  Thu May 28 23:47:37 CST 2020
	 */
	public Date getLastOperatordate() {
		return lastOperatordate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column roles.last_operatordate
	 * @param lastOperatordate  the value for roles.last_operatordate
	 * @mbg.generated  Thu May 28 23:47:37 CST 2020
	 */
	public void setLastOperatordate(Date lastOperatordate) {
		this.lastOperatordate = lastOperatordate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column roles.operator_empJobId
	 * @return  the value of roles.operator_empJobId
	 * @mbg.generated  Thu May 28 23:47:37 CST 2020
	 */
	public String getOperatorEmpjobid() {
		return operatorEmpjobid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column roles.operator_empJobId
	 * @param operatorEmpjobid  the value for roles.operator_empJobId
	 * @mbg.generated  Thu May 28 23:47:37 CST 2020
	 */
	public void setOperatorEmpjobid(String operatorEmpjobid) {
		this.operatorEmpjobid = operatorEmpjobid;
	}

	@Override
	public String toString() {
		return "Roles [roleId=" + roleId + ", roleName=" + roleName + ", roleDesc=" + roleDesc + "]";
	}

	public String getOperatorEmpName() {
		return operatorEmpName;
	}

	public void setOperatorEmpName(String operatorEmpName) {
		this.operatorEmpName = operatorEmpName;
	}
	
    
}