package com.lqs.hrm.entity;

import java.util.Date;

/**
 * 用户-角色实体类
 * @author luckyliuqs
 *
 */
public class UserRole {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_role.ur_id
	 * @mbg.generated  Fri May 29 00:31:01 CST 2020
	 */
	private Integer urId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_role.user_account
	 * @mbg.generated  Fri May 29 00:31:01 CST 2020
	 */
	private String userAccount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_role.role_id
	 * @mbg.generated  Fri May 29 00:31:01 CST 2020
	 */
	private Integer roleId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_role.last_operator_date
	 * @mbg.generated  Fri May 29 00:31:01 CST 2020
	 */
	private Date lastOperatorDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_role.operator_empJobId
	 * @mbg.generated  Fri May 29 00:31:01 CST 2020
	 */
	private String operatorEmpjobid;
	
	/**
	 * 操作人姓名
	 */
	private String operatorEmpName;
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_role.ur_id
	 * @return  the value of user_role.ur_id
	 * @mbg.generated  Fri May 29 00:31:01 CST 2020
	 */
	public Integer getUrId() {
		return urId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_role.ur_id
	 * @param urId  the value for user_role.ur_id
	 * @mbg.generated  Fri May 29 00:31:01 CST 2020
	 */
	public void setUrId(Integer urId) {
		this.urId = urId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_role.user_account
	 * @return  the value of user_role.user_account
	 * @mbg.generated  Fri May 29 00:31:01 CST 2020
	 */
	public String getUserAccount() {
		return userAccount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_role.user_account
	 * @param userAccount  the value for user_role.user_account
	 * @mbg.generated  Fri May 29 00:31:01 CST 2020
	 */
	public void setUserAccount(String userAccount) {
		this.userAccount = userAccount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_role.role_id
	 * @return  the value of user_role.role_id
	 * @mbg.generated  Fri May 29 00:31:01 CST 2020
	 */
	public Integer getRoleId() {
		return roleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_role.role_id
	 * @param roleId  the value for user_role.role_id
	 * @mbg.generated  Fri May 29 00:31:01 CST 2020
	 */
	public void setRoleId(Integer roleId) {
		this.roleId = roleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_role.last_operator_date
	 * @return  the value of user_role.last_operator_date
	 * @mbg.generated  Fri May 29 00:31:01 CST 2020
	 */
	public Date getLastOperatorDate() {
		return lastOperatorDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_role.last_operator_date
	 * @param lastOperatorDate  the value for user_role.last_operator_date
	 * @mbg.generated  Fri May 29 00:31:01 CST 2020
	 */
	public void setLastOperatorDate(Date lastOperatorDate) {
		this.lastOperatorDate = lastOperatorDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_role.operator_empJobId
	 * @return  the value of user_role.operator_empJobId
	 * @mbg.generated  Fri May 29 00:31:01 CST 2020
	 */
	public String getOperatorEmpjobid() {
		return operatorEmpjobid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_role.operator_empJobId
	 * @param operatorEmpjobid  the value for user_role.operator_empJobId
	 * @mbg.generated  Fri May 29 00:31:01 CST 2020
	 */
	public void setOperatorEmpjobid(String operatorEmpjobid) {
		this.operatorEmpjobid = operatorEmpjobid;
	}

	/**
	 * 设置用户姓名
	 */
	private String userName;
	/**
	 * 设置角色名称
	 */
	private String roleName;
	
	public String getUserName() {
		return userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getRoleName() {
		return roleName;
	}

	public void setRoleName(String roleName) {
		this.roleName = roleName;
	}

	public String getOperatorEmpName() {
		return operatorEmpName;
	}

	public void setOperatorEmpName(String operatorEmpName) {
		this.operatorEmpName = operatorEmpName;
	}
	
}