package com.lqs.hrm.entity;

import java.util.Date;

public class User {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.u_id
	 * @mbg.generated  Wed Mar 18 11:05:03 CST 2020
	 */
	private Integer uId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.u_account
	 * @mbg.generated  Wed Mar 18 11:05:03 CST 2020
	 */
	private String uAccount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.u_name
	 * @mbg.generated  Wed Mar 18 11:05:03 CST 2020
	 */
	private String uName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.u_password
	 * @mbg.generated  Wed Mar 18 11:05:03 CST 2020
	 */
	private String uPassword;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.u_photo
	 * @mbg.generated  Wed Mar 18 11:05:03 CST 2020
	 */
	private String uPhoto;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.u_roleId
	 * @mbg.generated  Wed Mar 18 11:05:03 CST 2020
	 */
	private Integer uRoleid;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.u_id
	 * @return  the value of user.u_id
	 * @mbg.generated  Wed Mar 18 11:05:03 CST 2020
	 */
	public Integer getuId() {
		return uId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.u_id
	 * @param uId  the value for user.u_id
	 * @mbg.generated  Wed Mar 18 11:05:03 CST 2020
	 */
	public void setuId(Integer uId) {
		this.uId = uId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.u_account
	 * @return  the value of user.u_account
	 * @mbg.generated  Wed Mar 18 11:05:03 CST 2020
	 */
	public String getuAccount() {
		return uAccount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.u_account
	 * @param uAccount  the value for user.u_account
	 * @mbg.generated  Wed Mar 18 11:05:03 CST 2020
	 */
	public void setuAccount(String uAccount) {
		this.uAccount = uAccount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.u_name
	 * @return  the value of user.u_name
	 * @mbg.generated  Wed Mar 18 11:05:03 CST 2020
	 */
	public String getuName() {
		return uName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.u_name
	 * @param uName  the value for user.u_name
	 * @mbg.generated  Wed Mar 18 11:05:03 CST 2020
	 */
	public void setuName(String uName) {
		this.uName = uName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.u_password
	 * @return  the value of user.u_password
	 * @mbg.generated  Wed Mar 18 11:05:03 CST 2020
	 */
	public String getuPassword() {
		return uPassword;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.u_password
	 * @param uPassword  the value for user.u_password
	 * @mbg.generated  Wed Mar 18 11:05:03 CST 2020
	 */
	public void setuPassword(String uPassword) {
		this.uPassword = uPassword;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.u_photo
	 * @return  the value of user.u_photo
	 * @mbg.generated  Wed Mar 18 11:05:03 CST 2020
	 */
	public String getuPhoto() {
		return uPhoto;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.u_photo
	 * @param uPhoto  the value for user.u_photo
	 * @mbg.generated  Wed Mar 18 11:05:03 CST 2020
	 */
	public void setuPhoto(String uPhoto) {
		this.uPhoto = uPhoto;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.u_roleId
	 * @return  the value of user.u_roleId
	 * @mbg.generated  Wed Mar 18 11:05:03 CST 2020
	 */
	public Integer getuRoleid() {
		return uRoleid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.u_roleId
	 * @param uRoleid  the value for user.u_roleId
	 * @mbg.generated  Wed Mar 18 11:05:03 CST 2020
	 */
	public void setuRoleid(Integer uRoleid) {
		this.uRoleid = uRoleid;
	}
}